config:
  default: true
  MD013:
    line_length: 88
    code_blocks: false
    tables: false
    headings: false
  MD033: false
  MD041: false
globs:
  - "README.md"
  - "DOCS.md"
  - "docs/mainpage.md"
  - "docs/cookbook.md"
  - "docs/static-toml-config.md"
  - "docs/feature-flags.md"
  - "examples/multi-device-project/README.md"
  - "examples/avr-board-matrix/README.md"
  - "examples/all-options-toml/README.md"
  - "examples/cookbook/README.md"
noBanner: true
noProgress: true
gitignore: true
