"""Reusable C++ code-rendering primitives."""

from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

    from .models import DeviceConfig


def line_comment_notice(source_path: Path) -> str:
    """Return the generated-file warning used in every emitted header."""
    return (
        "// Generated by tools/generate_lsh_static_config.py from "
        f"{source_path.name}. Do not edit by hand."
    )


def header_guard(path_fragment: str) -> str:
    """Build a deterministic include guard from a generated path."""
    guard = re.sub(r"[^A-Za-z0-9]+", "_", path_fragment).strip("_").upper()
    return f"LSH_GENERATED_{guard}"


def str_literal(value: str) -> str:
    """Escape a C++ string literal."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def u8(value: int) -> str:
    """Render an unsigned 8-bit integer literal."""
    return f"{value}U"


def u16(value: int) -> str:
    """Render an unsigned 16-bit integer literal."""
    return f"{value}U"


def u32(value: int) -> str:
    """Render an unsigned 32-bit integer literal."""
    return f"{value}UL"


def render_banner(file_path: str, source_path: Path) -> list[str]:
    """Render the small generated-header banner."""
    return [
        "/**",
        f" * @file    {Path(file_path).name}",
        " * @brief   Generated lsh-core static configuration. "
        "Edit the TOML source instead.",
        " */",
        "",
        line_comment_notice(source_path),
        "",
    ]


def consecutive_runs(
    index_value_pairs: Sequence[tuple[int, int]],
) -> list[tuple[int, int, int]]:
    """Group consecutive index/value pairs with the same arithmetic offset."""
    if not index_value_pairs:
        return []

    runs: list[tuple[int, int, int]] = []
    start_index, start_value = index_value_pairs[0]
    previous_index, previous_value = start_index, start_value
    offset = start_value - start_index

    for index, value in index_value_pairs[1:]:
        if (
            index == previous_index + 1
            and value == previous_value + 1
            and value - index == offset
        ):
            previous_index, previous_value = index, value
            continue
        runs.append((start_index, previous_index, offset))
        start_index, start_value = index, value
        previous_index, previous_value = index, value
        offset = value - index

    runs.append((start_index, previous_index, offset))
    return runs


def render_range_condition(var_name: str, start: int, end: int) -> str:
    """Render a compact C++ range condition."""
    if start == end:
        return f"{var_name} == {u8(start)}"
    if start == 0:
        return f"{var_name} < {u8(end + 1)}"
    return f"{var_name} >= {u8(start)} && {var_name} <= {u8(end)}"


def render_value_expression(var_name: str, offset: int) -> str:
    """Render the value expression for a branch-based generated accessor."""
    if offset == 0:
        return var_name
    if offset > 0:
        return f"static_cast<uint8_t>({var_name} + {u8(offset)})"
    return f"static_cast<uint8_t>({var_name} - {u8(abs(offset))})"


def render_run_value_expression(
    var_name: str, start: int, end: int, offset: int
) -> str:
    """Render a constant for singleton branches, arithmetic otherwise."""
    if start == end:
        return u8(start + offset)
    return render_value_expression(var_name, offset)


def render_index_to_value_function(
    function_name: str, param_name: str, values: Sequence[int], invalid: str
) -> list[str]:
    """Render an index-to-ID accessor without emitting a RAM table."""
    lines = [f"auto {function_name}(uint8_t {param_name}) noexcept -> uint8_t", "{"]
    if not values:
        lines.extend(
            [f"    static_cast<void>({param_name});", f"    return {invalid};", "}"]
        )
        return lines

    pairs = list(enumerate(values))
    runs = consecutive_runs(pairs)
    for run_index, (start, end, offset) in enumerate(runs):
        condition = render_range_condition(param_name, start, end)
        value = render_run_value_expression(param_name, start, end, offset)
        if run_index == len(runs) - 1:
            if run_index != 0:
                lines.append("")
            lines.append(f"    return {condition} ? {value} : {invalid};")
            break
        if run_index != 0:
            lines.append("")
        lines.extend(
            [f"    if ({condition})", "    {", f"        return {value};", "    }"]
        )
    lines.append("}")
    return lines


def render_lookup_function(
    function_name: str, param_name: str, id_to_index: dict[int, int]
) -> list[str]:
    """Render an ID-to-index accessor without emitting a RAM table."""
    lines = [f"auto {function_name}(uint8_t {param_name}) noexcept -> uint8_t", "{"]
    if not id_to_index:
        lines.extend(
            [f"    static_cast<void>({param_name});", "    return UINT8_MAX;", "}"]
        )
        return lines

    pairs = sorted(id_to_index.items())
    id_index_pairs = [(item_id, index) for item_id, index in pairs]
    runs = consecutive_runs(id_index_pairs)
    for run_index, (start_id, end_id, offset) in enumerate(runs):
        condition = render_range_condition(param_name, start_id, end_id)
        value = render_run_value_expression(param_name, start_id, end_id, offset)
        if run_index == len(runs) - 1:
            if run_index != 0:
                lines.append("")
            lines.append(f"    return {condition} ? {value} : UINT8_MAX;")
            break
        if run_index != 0:
            lines.append("")
        lines.extend(
            [f"    if ({condition})", "    {", f"        return {value};", "    }"]
        )
    lines.append("}")
    return lines


def render_u8_value_group_function(
    function_name: str,
    param_name: str,
    values: Sequence[int],
    invalid: str,
) -> list[str]:
    """Render a uint8_t accessor by grouping indexes that share one value."""
    lines = [f"auto {function_name}(uint8_t {param_name}) noexcept -> uint8_t", "{"]
    value_to_indexes: dict[int, list[int]] = {}
    invalid_value = int(invalid.removesuffix("U")) if invalid.endswith("U") else None
    for index, value in enumerate(values):
        if invalid_value is not None and value == invalid_value:
            continue
        value_to_indexes.setdefault(value, []).append(index)

    if not value_to_indexes:
        lines.extend(
            [f"    static_cast<void>({param_name});", f"    return {invalid};", "}"]
        )
        return lines

    groups = sorted(value_to_indexes.items(), key=lambda item: min(item[1]))
    for group_index, (value, indexes) in enumerate(groups):
        condition = render_values_condition(param_name, indexes)
        if group_index != 0:
            lines.append("")
        lines.extend(
            [f"    if ({condition})", "    {", f"        return {u8(value)};", "    }"]
        )
    lines.append("")
    lines.append(f"    return {invalid};")
    lines.append("}")
    return lines


def grouped_consecutive_values(values: Sequence[int]) -> list[tuple[int, int]]:
    """Group integer values into inclusive consecutive ranges."""
    if not values:
        return []
    sorted_values = sorted(values)
    groups: list[tuple[int, int]] = []
    start = sorted_values[0]
    previous = start
    for value in sorted_values[1:]:
        if value == previous + 1:
            previous = value
            continue
        groups.append((start, previous))
        start = previous = value
    groups.append((start, previous))
    return groups


def render_values_condition(var_name: str, values: Sequence[int]) -> str:
    """Render an equality/range condition for a set of integer values."""
    parts = [
        render_range_condition(var_name, start, end)
        for start, end in grouped_consecutive_values(values)
    ]
    if not parts:
        return "false"
    if len(parts) > 1:
        parts = [f"({part})" for part in parts]
    return " || ".join(parts)


def render_timer_function(
    device: DeviceConfig, actuator_indexes: dict[str, int]
) -> list[str]:
    """Render the static auto-off timer accessor."""
    timer_to_indexes: dict[int, list[int]] = {}
    for actuator in device.actuators:
        if actuator.auto_off_ms is not None:
            timer_to_indexes.setdefault(actuator.auto_off_ms, []).append(
                actuator_indexes[actuator.name]
            )

    lines = ["auto getAutoOffTimer(uint8_t actuatorIndex) noexcept -> uint32_t", "{"]
    if not timer_to_indexes:
        lines.extend(["    static_cast<void>(actuatorIndex);", "    return 0UL;", "}"])
        return lines

    groups = sorted(timer_to_indexes.items(), key=lambda item: min(item[1]))
    for group_index, (timer, indexes) in enumerate(groups):
        condition = render_values_condition("actuatorIndex", indexes)
        if group_index == len(groups) - 1:
            if group_index != 0:
                lines.append("")
            lines.append(f"    return {condition} ? {u32(timer)} : 0UL;")
            break
        if group_index != 0:
            lines.append("")
        lines.extend(
            [f"    if ({condition})", "    {", f"        return {u32(timer)};", "    }"]
        )
    lines.append("}")
    return lines


def render_enum_accessor(
    function_name: str,
    param_name: str,
    values: Sequence[str],
    enum_name: str,
    default_value: str,
) -> list[str]:
    """Render a generated enum accessor with only non-default branches."""
    lines = [
        (
            f"auto {function_name}(uint8_t {param_name}) noexcept "
            f"-> constants::{enum_name}"
        ),
        "{",
    ]
    non_default: dict[str, list[int]] = {}
    for index, value in enumerate(values):
        if value != default_value:
            non_default.setdefault(value, []).append(index)

    if not non_default:
        lines.extend(
            [
                f"    static_cast<void>({param_name});",
                f"    return constants::{enum_name}::{default_value};",
                "}",
            ]
        )
        return lines

    groups = sorted(non_default.items(), key=lambda item: min(item[1]))
    for group_index, (value, indexes) in enumerate(groups):
        condition = render_values_condition(param_name, indexes)
        if group_index != 0:
            lines.append("")
        lines.extend(
            [
                f"    if ({condition})",
                "    {",
                f"        return constants::{enum_name}::{value};",
                "    }",
            ]
        )
    lines.append("")
    lines.append(f"    return constants::{enum_name}::{default_value};")
    lines.append("}")
    return lines


def append_section(lines: list[str], section: Sequence[str]) -> None:
    """Append a generated function section separated by one blank line."""
    if lines and lines[-1] != "":
        lines.append("")
    lines.extend(section)
