[platformio]
description = "Representative Arduino AVR compatibility matrix for lsh-core"
default_envs = mega2560_fast_release, uno_release, nano_release

[common_base]
platform = atmelavr
framework = arduino

lib_deps = lsh-core=symlink://../..

extra_scripts = pre:../../tools/platformio_lsh_static_config.py
custom_lsh_config = lsh_devices.toml

build_src_filter = +<*>

check_skip_packages = yes
check_flags =
    cppcheck: --suppress=syntaxError:*function_traits.h

build_unflags = -std=gnu++11 -std=c++11
build_flags =
    -I include
    -std=gnu++17

[env:mega2560_fast_release]
extends = common_base
board = megaatmega2560
custom_lsh_device = mega2560_fast
build_type = release
build_flags =
    ${common_base.build_flags}
    -D NDEBUG

[env:uno_release]
extends = common_base
board = uno
custom_lsh_device = atmega328p_basic
build_type = release
build_flags =
    ${common_base.build_flags}
    -D NDEBUG

[env:nano_release]
extends = common_base
board = nanoatmega328
custom_lsh_device = atmega328p_basic
build_type = release
build_flags =
    ${common_base.build_flags}
    -D NDEBUG
