/**
 * @file    lsh_user_config.hpp
 * @brief   Generated lsh-core static configuration. Edit the TOML source instead.
 */

// Generated by tools/generate_lsh_static_config.py from lsh_devices.toml. Do not edit by hand.

#ifndef LSH_GENERATED_LSH_USER_CONFIG_HPP
#define LSH_GENERATED_LSH_USER_CONFIG_HPP

#if defined(LSH_BUILD_KITCHEN)
#include "lsh_configs/kitchen_config.hpp"
#else
// Available profiles: LSH_BUILD_KITCHEN.
#error "No lsh-core device profile selected. Define exactly one generated LSH_BUILD_* macro."
#endif

#endif  // LSH_GENERATED_LSH_USER_CONFIG_HPP
