/**
 * @file    lsh_static_config_router.hpp
 * @brief   Generated lsh-core static configuration. Edit the TOML source instead.
 */

// Generated by tools/generate_lsh_static_config.py from lsh_devices.toml. Do not edit by hand.

// Intentionally no include guard: lsh-core includes this router twice
// with different pass macros. A conventional guard would make the
// implementation pass disappear after the resource pass.

#if defined(LSH_BUILD_KITCHEN)
#include "lsh_configs/kitchen_static_config.hpp"
#else
// Available profiles: LSH_BUILD_KITCHEN.
#error "No lsh-core static profile selected. Define exactly one generated LSH_BUILD_* macro."
#endif
