/**
 * @file    kitchen_config.hpp
 * @brief   Generated lsh-core static configuration. Edit the TOML source instead.
 */

// Generated by tools/generate_lsh_static_config.py from lsh_devices.toml. Do not edit by hand.

#ifndef LSH_GENERATED_LSH_CONFIGS_KITCHEN_CONFIG_HPP
#define LSH_GENERATED_LSH_CONFIGS_KITCHEN_CONFIG_HPP

#define LSH_HARDWARE_INCLUDE <Controllino.h>
#include LSH_HARDWARE_INCLUDE

static constexpr auto LSH_DEVICE_NAME() -> const char *
{
    return "kitchen";
}

static constexpr auto LSH_COM_SERIAL() -> HardwareSerial *
{
    return &Serial2;
}

static constexpr auto LSH_DEBUG_SERIAL() -> HardwareSerial *
{
    return &Serial;
}

#endif  // LSH_GENERATED_LSH_CONFIGS_KITCHEN_CONFIG_HPP
