/**
 * @file    kitchen_static_config.hpp
 * @brief   Generated lsh-core static configuration. Edit the TOML source instead.
 */

// Generated by tools/generate_lsh_static_config.py from lsh_devices.toml. Do not edit by hand.

#if defined(LSH_STATIC_CONFIG_RESOURCE_PASS)

#ifndef LSH_GENERATED_LSH_CONFIGS_KITCHEN_STATIC_CONFIG_HPP_RESOURCE
#define LSH_GENERATED_LSH_CONFIGS_KITCHEN_STATIC_CONFIG_HPP_RESOURCE

#define LSH_STATIC_CONFIG_CLICKABLES 5
#define LSH_STATIC_CONFIG_ACTUATORS 7
#define LSH_STATIC_CONFIG_INDICATORS 3
#define LSH_STATIC_CONFIG_MAX_CLICKABLE_ID 5
#define LSH_STATIC_CONFIG_MAX_ACTUATOR_ID 7
#define LSH_STATIC_CONFIG_SHORT_CLICK_ACTUATOR_LINKS 7
#define LSH_STATIC_CONFIG_LONG_CLICK_ACTUATOR_LINKS 10
#define LSH_STATIC_CONFIG_SUPER_LONG_CLICK_ACTUATOR_LINKS 5
#define LSH_STATIC_CONFIG_INDICATOR_ACTUATOR_LINKS 6
#define LSH_STATIC_CONFIG_AUTO_OFF_ACTUATORS 1
#define LSH_STATIC_CONFIG_PULSE_ACTUATORS 1
#define LSH_STATIC_CONFIG_ACTIVE_NETWORK_CLICKS 1
#define LSH_STATIC_CONFIG_DISABLE_NETWORK_CLICKS 0

#endif  // LSH_GENERATED_LSH_CONFIGS_KITCHEN_STATIC_CONFIG_HPP_RESOURCE

#elif defined(LSH_STATIC_CONFIG_IMPLEMENTATION_PASS)

#ifndef LSH_GENERATED_LSH_CONFIGS_KITCHEN_STATIC_CONFIG_HPP_IMPLEMENTATION
#define LSH_GENERATED_LSH_CONFIGS_KITCHEN_STATIC_CONFIG_HPP_IMPLEMENTATION

#include "communication/bridge_serial.hpp"
#include "config/static_config.hpp"
#include "core/network_clicks.hpp"
#include "device/actuator_manager.hpp"
#include "device/clickable_manager.hpp"
#include "device/indicator_manager.hpp"
#include "lsh_user_macros.hpp"
#include "util/constants/click_detection.hpp"
#include "util/constants/click_results.hpp"
#include "util/constants/click_types.hpp"
#include "util/constants/timing.hpp"
#include "util/debug/debug.hpp"
#include "util/time_keeper.hpp"

#if defined(__AVR__)
#include <avr/pgmspace.h>
#define LSH_STATIC_CONFIG_PROGMEM PROGMEM
#define LSH_STATIC_CONFIG_READ_BYTE(address) pgm_read_byte(address)
#else
#define LSH_STATIC_CONFIG_PROGMEM
#define LSH_STATIC_CONFIG_READ_BYTE(address) (*(address))
#endif

namespace
{
// clang-format off
const uint8_t DETAILS_JSON_PAYLOAD[] LSH_STATIC_CONFIG_PROGMEM = {
    0x7BU, 0x22U, 0x70U, 0x22U, 0x3AU, 0x31U, 0x2CU, 0x22U, 0x76U, 0x22U, 0x3AU, 0x33U,
    0x2CU, 0x22U, 0x6EU, 0x22U, 0x3AU, 0x22U, 0x6BU, 0x69U, 0x74U, 0x63U, 0x68U, 0x65U,
    0x6EU, 0x22U, 0x2CU, 0x22U, 0x61U, 0x22U, 0x3AU, 0x5BU, 0x31U, 0x2CU, 0x32U, 0x2CU,
    0x33U, 0x2CU, 0x34U, 0x2CU, 0x35U, 0x2CU, 0x36U, 0x2CU, 0x37U, 0x5DU, 0x2CU, 0x22U,
    0x62U, 0x22U, 0x3AU, 0x5BU, 0x31U, 0x2CU, 0x32U, 0x2CU, 0x33U, 0x2CU, 0x34U, 0x2CU,
    0x35U, 0x5DU, 0x7DU, 0x0AU
};

const uint8_t DETAILS_MSGPACK_PAYLOAD[] LSH_STATIC_CONFIG_PROGMEM = {
    0xC0U, 0x85U, 0xA1U, 0x70U, 0x01U, 0xA1U, 0x76U, 0x03U, 0xA1U, 0x6EU, 0xA7U, 0x6BU,
    0x69U, 0x74U, 0x63U, 0x68U, 0x65U, 0x6EU, 0xA1U, 0x61U, 0x97U, 0x01U, 0x02U, 0x03U,
    0x04U, 0x05U, 0x06U, 0x07U, 0xA1U, 0x62U, 0x95U, 0x01U, 0x02U, 0x03U, 0x04U, 0x05U,
    0xC0U
};
// clang-format on

constexpr uint16_t LSH_STATIC_CONFIG_UNROLLED_PAYLOAD_LIMIT = 128U;

template <uint16_t ByteIndex, uint16_t PayloadSize> struct GeneratedPayloadByteWriter
{
    static auto write(const uint8_t (&payload)[PayloadSize]) noexcept -> bool
    {
        return CONFIG_COM_SERIAL->HardwareSerial::write(LSH_STATIC_CONFIG_READ_BYTE(&payload[ByteIndex])) == 1U &&
               GeneratedPayloadByteWriter<static_cast<uint16_t>(ByteIndex + 1U), PayloadSize>::write(payload);
    }
};

template <uint16_t PayloadSize> struct GeneratedPayloadByteWriter<PayloadSize, PayloadSize>
{
    static auto write(const uint8_t (&payload)[PayloadSize]) noexcept -> bool
    {
        static_cast<void>(payload);
        return true;
    }
};

template <uint16_t PayloadSize> auto writeGeneratedPayloadLoop(const uint8_t (&payload)[PayloadSize]) noexcept -> bool
{
    for (uint16_t byteIndex = 0U; byteIndex < PayloadSize; ++byteIndex)
    {
        if (CONFIG_COM_SERIAL->HardwareSerial::write(LSH_STATIC_CONFIG_READ_BYTE(&payload[byteIndex])) != 1U)
        {
            return false;
        }
    }
    return true;
}

template <uint16_t PayloadSize> auto writeGeneratedPayload(const uint8_t (&payload)[PayloadSize]) noexcept -> bool
{
    static_assert(PayloadSize > 0U, "Generated static payloads must not be empty.");
    if constexpr (PayloadSize <= LSH_STATIC_CONFIG_UNROLLED_PAYLOAD_LIMIT)
    {
        return GeneratedPayloadByteWriter<0U, PayloadSize>::write(payload);
    }
    return writeGeneratedPayloadLoop(payload);
}

LSH_ACTUATOR(actuator0_ceiling, CONTROLLINO_R0);
LSH_ACTUATOR(actuator1_worktop, CONTROLLINO_R1);
Actuator actuator2_ambient(::lsh::core::PinTag<(CONTROLLINO_R2)>{}, true);
LSH_ACTUATOR(actuator3_door_strike, CONTROLLINO_R3);
LSH_ACTUATOR(actuator4_blind_up, CONTROLLINO_R4);
LSH_ACTUATOR(actuator5_blind_down, CONTROLLINO_R5);
LSH_ACTUATOR(actuator6_service, CONTROLLINO_R6);

LSH_BUTTON(button0_door, CONTROLLINO_A0);
LSH_BUTTON(button1_worktop, CONTROLLINO_A1);
LSH_BUTTON(button2_strike, CONTROLLINO_A2);
LSH_BUTTON(button3_blind_up, CONTROLLINO_A3);
LSH_BUTTON(button4_blind_down, CONTROLLINO_A4);

LSH_INDICATOR(indicator0_ceiling_led, CONTROLLINO_D0);
LSH_INDICATOR(indicator1_any_light_led, CONTROLLINO_D1);
LSH_INDICATOR(indicator2_cooking_led, CONTROLLINO_D2);
}  // namespace

namespace lsh::core::static_config
{
auto getActuatorId(uint8_t actuatorIndex) noexcept -> uint8_t
{
    return actuatorIndex < 7U ? static_cast<uint8_t>(actuatorIndex + 1U) : 0U;
}

auto getClickableId(uint8_t clickableIndex) noexcept -> uint8_t
{
    return clickableIndex < 5U ? static_cast<uint8_t>(clickableIndex + 1U) : 0U;
}

auto getActuatorIndexById(uint8_t actuatorId) noexcept -> uint8_t
{
    return actuatorId >= 1U && actuatorId <= 7U ? static_cast<uint8_t>(actuatorId - 1U) : UINT8_MAX;
}

auto getClickableIndexById(uint8_t clickableId) noexcept -> uint8_t
{
    return clickableId >= 1U && clickableId <= 5U ? static_cast<uint8_t>(clickableId - 1U) : UINT8_MAX;
}

auto getAutoOffActuatorIndex(uint8_t autoOffIndex) noexcept -> uint8_t
{
    return autoOffIndex == 0U ? 1U : UINT8_MAX;
}

auto getAutoOffIndexByActuatorIndex(uint8_t actuatorIndex) noexcept -> uint8_t
{
    return actuatorIndex == 1U ? 0U : UINT8_MAX;
}

auto getAutoOffTimer(uint8_t actuatorIndex) noexcept -> uint32_t
{
    return actuatorIndex == 1U ? 2700000UL : 0UL;
}

auto getIndicatorActuatorLinkCount(uint8_t indicatorIndex) noexcept -> uint8_t
{
    if (indicatorIndex == 0U)
    {
        return 1U;
    }

    if (indicatorIndex == 1U)
    {
        return 3U;
    }

    if (indicatorIndex == 2U)
    {
        return 2U;
    }

    return 0U;
}

auto writeDetailsPayload() noexcept -> bool
{
#ifdef CONFIG_MSG_PACK
    return writeGeneratedPayload(DETAILS_MSGPACK_PAYLOAD);
#else
    return writeGeneratedPayload(DETAILS_JSON_PAYLOAD);
#endif
}

static uint16_t pulseRemaining_ms[CONFIG_PULSE_STORAGE_CAPACITY] = {};
static uint8_t activePulseActuators = 0U;

[[nodiscard]] __attribute__((always_inline)) inline auto actuator0_ceilingActionSet(bool state) noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator0_ceilingActionSet(bool state, uint32_t actionNow) noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator0_ceilingActionToggle() noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator0_ceilingActionToggle(uint32_t actionNow) noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator1_worktopActionSet(bool state) noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator1_worktopActionSet(bool state, uint32_t actionNow) noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator1_worktopActionToggle() noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator1_worktopActionToggle(uint32_t actionNow) noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator2_ambientActionSet(bool state) noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator2_ambientActionSet(bool state, uint32_t actionNow) noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator2_ambientActionToggle() noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator2_ambientActionToggle(uint32_t actionNow) noexcept -> bool;
[[nodiscard]] inline auto actuator3_door_strikeActionSet(bool state) noexcept -> bool;
[[nodiscard]] inline auto actuator3_door_strikeActionSet(bool state, uint32_t actionNow) noexcept -> bool;
[[nodiscard]] inline auto actuator3_door_strikeActionToggle() noexcept -> bool;
[[nodiscard]] inline auto actuator3_door_strikeActionToggle(uint32_t actionNow) noexcept -> bool;
[[nodiscard]] inline auto actuator4_blind_upActionSet(bool state) noexcept -> bool;
[[nodiscard]] inline auto actuator4_blind_upActionSet(bool state, uint32_t actionNow) noexcept -> bool;
[[nodiscard]] inline auto actuator4_blind_upActionToggle() noexcept -> bool;
[[nodiscard]] inline auto actuator4_blind_upActionToggle(uint32_t actionNow) noexcept -> bool;
[[nodiscard]] inline auto actuator5_blind_downActionSet(bool state) noexcept -> bool;
[[nodiscard]] inline auto actuator5_blind_downActionSet(bool state, uint32_t actionNow) noexcept -> bool;
[[nodiscard]] inline auto actuator5_blind_downActionToggle() noexcept -> bool;
[[nodiscard]] inline auto actuator5_blind_downActionToggle(uint32_t actionNow) noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator6_serviceActionSet(bool state) noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator6_serviceActionSet(bool state, uint32_t actionNow) noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator6_serviceActionToggle() noexcept -> bool;
[[nodiscard]] __attribute__((always_inline)) inline auto actuator6_serviceActionToggle(uint32_t actionNow) noexcept -> bool;

[[nodiscard]] __attribute__((always_inline)) inline auto actuator0_ceilingActionSet(bool state) noexcept -> bool
{
    return actuator0_ceiling.setStateStatic<0U>(state);
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator0_ceilingActionSet(bool state, uint32_t actionNow) noexcept -> bool
{
    bool anyActuatorChangedState = false;
    anyActuatorChangedState |= actuator0_ceiling.setStateStatic<0U>(state, actionNow);
    return anyActuatorChangedState;
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator0_ceilingActionToggle() noexcept -> bool
{
    return actuator0_ceiling.toggleStateStatic<0U>();
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator0_ceilingActionToggle(uint32_t actionNow) noexcept -> bool
{
    return actuator0_ceilingActionSet(!actuator0_ceiling.getState(), actionNow);
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator1_worktopActionSet(bool state) noexcept -> bool
{
    return actuator1_worktop.setStateStatic<1U>(state);
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator1_worktopActionSet(bool state, uint32_t actionNow) noexcept -> bool
{
    bool anyActuatorChangedState = false;
    anyActuatorChangedState |= actuator1_worktop.setStateStatic<1U>(state, actionNow);
    return anyActuatorChangedState;
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator1_worktopActionToggle() noexcept -> bool
{
    return actuator1_worktop.toggleStateStatic<1U>();
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator1_worktopActionToggle(uint32_t actionNow) noexcept -> bool
{
    return actuator1_worktopActionSet(!actuator1_worktop.getState(), actionNow);
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator2_ambientActionSet(bool state) noexcept -> bool
{
    return actuator2_ambient.setStateStatic<2U>(state);
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator2_ambientActionSet(bool state, uint32_t actionNow) noexcept -> bool
{
    bool anyActuatorChangedState = false;
    anyActuatorChangedState |= actuator2_ambient.setStateStatic<2U>(state, actionNow);
    return anyActuatorChangedState;
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator2_ambientActionToggle() noexcept -> bool
{
    return actuator2_ambient.toggleStateStatic<2U>();
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator2_ambientActionToggle(uint32_t actionNow) noexcept -> bool
{
    return actuator2_ambientActionSet(!actuator2_ambient.getState(), actionNow);
}

[[nodiscard]] inline auto actuator3_door_strikeActionSet(bool state) noexcept -> bool
{
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
    const uint32_t actionNow = timeKeeper::getTime();
#else
    constexpr uint32_t actionNow = 0U;
#endif
    return actuator3_door_strikeActionSet(state, actionNow);
}

[[nodiscard]] inline auto actuator3_door_strikeActionSet(bool state, uint32_t actionNow) noexcept -> bool
{
    bool anyActuatorChangedState = false;
    static_assert(300U >= constants::timings::ACTUATOR_DEBOUNCE_TIME_MS,
                  "Pulse duration must be greater than or equal to actuator debounce.");
    if (state)
    {
        const bool actuatorWasOn = actuator3_door_strike.getState();
        const bool pulseWasActive = pulseRemaining_ms[0U] != 0U;
        const bool pulseStarted = actuator3_door_strike.setStateStatic<3U>(true, actionNow);
        anyActuatorChangedState |= pulseStarted;
        if (pulseStarted || actuatorWasOn)
        {
            if (!pulseWasActive)
            {
                ++activePulseActuators;
            }
            pulseRemaining_ms[0U] = 300U;
        }
    }
    else
    {
        if (pulseRemaining_ms[0U] != 0U)
        {
            pulseRemaining_ms[0U] = 0U;
            --activePulseActuators;
        }
        anyActuatorChangedState |= actuator3_door_strike.setStateStatic<3U>(false, actionNow);
    }
    return anyActuatorChangedState;
}

[[nodiscard]] inline auto actuator3_door_strikeActionToggle() noexcept -> bool
{
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
    const uint32_t actionNow = timeKeeper::getTime();
#else
    constexpr uint32_t actionNow = 0U;
#endif
    return actuator3_door_strikeActionToggle(actionNow);
}

[[nodiscard]] inline auto actuator3_door_strikeActionToggle(uint32_t actionNow) noexcept -> bool
{
    return actuator3_door_strikeActionSet(!actuator3_door_strike.getState(), actionNow);
}

[[nodiscard]] inline auto actuator4_blind_upActionSet(bool state) noexcept -> bool
{
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
    const uint32_t actionNow = timeKeeper::getTime();
#else
    constexpr uint32_t actionNow = 0U;
#endif
    return actuator4_blind_upActionSet(state, actionNow);
}

[[nodiscard]] inline auto actuator4_blind_upActionSet(bool state, uint32_t actionNow) noexcept -> bool
{
    bool anyActuatorChangedState = false;
    if (state)
    {
        anyActuatorChangedState |= actuator5_blind_downActionSet(false, actionNow);
    }
    anyActuatorChangedState |= actuator4_blind_up.setStateStatic<4U>(state, actionNow);
    return anyActuatorChangedState;
}

[[nodiscard]] inline auto actuator4_blind_upActionToggle() noexcept -> bool
{
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
    const uint32_t actionNow = timeKeeper::getTime();
#else
    constexpr uint32_t actionNow = 0U;
#endif
    return actuator4_blind_upActionToggle(actionNow);
}

[[nodiscard]] inline auto actuator4_blind_upActionToggle(uint32_t actionNow) noexcept -> bool
{
    return actuator4_blind_upActionSet(!actuator4_blind_up.getState(), actionNow);
}

[[nodiscard]] inline auto actuator5_blind_downActionSet(bool state) noexcept -> bool
{
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
    const uint32_t actionNow = timeKeeper::getTime();
#else
    constexpr uint32_t actionNow = 0U;
#endif
    return actuator5_blind_downActionSet(state, actionNow);
}

[[nodiscard]] inline auto actuator5_blind_downActionSet(bool state, uint32_t actionNow) noexcept -> bool
{
    bool anyActuatorChangedState = false;
    if (state)
    {
        anyActuatorChangedState |= actuator4_blind_upActionSet(false, actionNow);
    }
    anyActuatorChangedState |= actuator5_blind_down.setStateStatic<5U>(state, actionNow);
    return anyActuatorChangedState;
}

[[nodiscard]] inline auto actuator5_blind_downActionToggle() noexcept -> bool
{
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
    const uint32_t actionNow = timeKeeper::getTime();
#else
    constexpr uint32_t actionNow = 0U;
#endif
    return actuator5_blind_downActionToggle(actionNow);
}

[[nodiscard]] inline auto actuator5_blind_downActionToggle(uint32_t actionNow) noexcept -> bool
{
    return actuator5_blind_downActionSet(!actuator5_blind_down.getState(), actionNow);
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator6_serviceActionSet(bool state) noexcept -> bool
{
    return actuator6_service.setStateStatic<6U>(state);
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator6_serviceActionSet(bool state, uint32_t actionNow) noexcept -> bool
{
    bool anyActuatorChangedState = false;
    anyActuatorChangedState |= actuator6_service.setStateStatic<6U>(state, actionNow);
    return anyActuatorChangedState;
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator6_serviceActionToggle() noexcept -> bool
{
    return actuator6_service.toggleStateStatic<6U>();
}

[[nodiscard]] __attribute__((always_inline)) inline auto actuator6_serviceActionToggle(uint32_t actionNow) noexcept -> bool
{
    return actuator6_serviceActionSet(!actuator6_service.getState(), actionNow);
}

auto runShortClick(uint8_t clickableIndex) noexcept -> bool
{
    switch (clickableIndex)
    {
    case 0U:
    {
        return actuator0_ceilingActionToggle();
    }
    case 1U:
    {
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= actuator0_ceilingActionToggle(actionNow);
        anyActuatorChangedState |= actuator1_worktopActionToggle(actionNow);
        anyActuatorChangedState |= actuator2_ambientActionToggle(actionNow);
        return anyActuatorChangedState;
    }
    case 2U:
    {
        return actuator3_door_strikeActionToggle();
    }
    case 3U:
    {
        return actuator4_blind_upActionToggle();
    }
    case 4U:
    {
        return actuator5_blind_downActionToggle();
    }
    default:
        return false;
    }
}

auto runLongClick(uint8_t clickableIndex) noexcept -> bool
{
    switch (clickableIndex)
    {
    case 0U:
    {
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= actuator0_ceilingActionSet(false, actionNow);
        anyActuatorChangedState |= actuator1_worktopActionSet(false, actionNow);
        anyActuatorChangedState |= actuator2_ambientActionSet(false, actionNow);
        return anyActuatorChangedState;
    }
    case 1U:
    {
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= actuator2_ambientActionSet(false, actionNow);
        anyActuatorChangedState |= actuator0_ceilingActionSet(true, actionNow);
        anyActuatorChangedState |= actuator1_worktopActionSet(true, actionNow);
        return anyActuatorChangedState;
    }
    case 2U:
    {
        return false;
    }
    case 3U:
    {
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= actuator4_blind_upActionSet(false, actionNow);
        anyActuatorChangedState |= actuator5_blind_downActionSet(false, actionNow);
        return anyActuatorChangedState;
    }
    case 4U:
    {
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= actuator4_blind_upActionSet(false, actionNow);
        anyActuatorChangedState |= actuator5_blind_downActionSet(false, actionNow);
        return anyActuatorChangedState;
    }
    default:
        return false;
    }
}

auto turnOffAllActuators() noexcept -> bool
{
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
    const uint32_t actionNow = timeKeeper::getTime();
#else
    constexpr uint32_t actionNow = 0U;
#endif
    bool anyActuatorChangedState = false;
    anyActuatorChangedState |= actuator0_ceilingActionSet(false, actionNow);
    anyActuatorChangedState |= actuator1_worktopActionSet(false, actionNow);
    anyActuatorChangedState |= actuator2_ambientActionSet(false, actionNow);
    anyActuatorChangedState |= actuator3_door_strikeActionSet(false, actionNow);
    anyActuatorChangedState |= actuator4_blind_upActionSet(false, actionNow);
    anyActuatorChangedState |= actuator5_blind_downActionSet(false, actionNow);
    anyActuatorChangedState |= actuator6_serviceActionSet(false, actionNow);
    return anyActuatorChangedState;
}

auto turnOffUnprotectedActuators() noexcept -> bool
{
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
    const uint32_t actionNow = timeKeeper::getTime();
#else
    constexpr uint32_t actionNow = 0U;
#endif
    bool anyActuatorChangedState = false;
    anyActuatorChangedState |= actuator0_ceilingActionSet(false, actionNow);
    anyActuatorChangedState |= actuator1_worktopActionSet(false, actionNow);
    anyActuatorChangedState |= actuator2_ambientActionSet(false, actionNow);
    anyActuatorChangedState |= actuator3_door_strikeActionSet(false, actionNow);
    anyActuatorChangedState |= actuator4_blind_upActionSet(false, actionNow);
    anyActuatorChangedState |= actuator5_blind_downActionSet(false, actionNow);
    return anyActuatorChangedState;
}

auto runSuperLongClick(uint8_t clickableIndex) noexcept -> bool
{
    switch (clickableIndex)
    {
    case 0U:
    {
        return turnOffUnprotectedActuators();
    }
    case 1U:
    {
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= actuator0_ceilingActionSet(false, actionNow);
        anyActuatorChangedState |= actuator1_worktopActionSet(false, actionNow);
        anyActuatorChangedState |= actuator2_ambientActionSet(false, actionNow);
        anyActuatorChangedState |= actuator4_blind_upActionSet(false, actionNow);
        anyActuatorChangedState |= actuator5_blind_downActionSet(false, actionNow);
        return anyActuatorChangedState;
    }
    default:
        return false;
    }
}

auto runClick(uint8_t clickableIndex, constants::ClickType clickType) noexcept -> bool
{
    switch (clickType)
    {
    case constants::ClickType::SHORT:
        return runShortClick(clickableIndex);
    case constants::ClickType::LONG:
        return runLongClick(clickableIndex);
    case constants::ClickType::SUPER_LONG:
        return runSuperLongClick(clickableIndex);
    default:
        return false;
    }
}

auto runNetworkClickFallback(uint8_t clickableIndex, constants::ClickType clickType) noexcept -> bool
{
    static_cast<void>(clickableIndex);
    static_cast<void>(clickType);
    return false;
}

auto getNetworkClickSlotCount(uint8_t clickableIndex) noexcept -> uint8_t
{
    if (clickableIndex == 2U)
    {
        return 1U;
    }

    return 0U;
}

auto getNetworkClickSlotIndex(uint8_t clickableIndex, constants::ClickType clickType) noexcept -> uint8_t
{
    switch (clickType)
    {
    case constants::ClickType::LONG:
    {
        switch (clickableIndex)
        {
        case 2U:
            return 0U;
        default:
            return UINT8_MAX;
        }
    }
    case constants::ClickType::SUPER_LONG:
    {
        return UINT8_MAX;
    }
    default:
        return UINT8_MAX;
    }
}

auto getNetworkClickClickableIndex(uint8_t slotIndex) noexcept -> uint8_t
{
    if (slotIndex == 0U)
    {
        return 2U;
    }

    return UINT8_MAX;
}

auto getNetworkClickType(uint8_t slotIndex) noexcept -> constants::ClickType
{
    if (slotIndex == 0U)
    {
        return constants::ClickType::LONG;
    }

    return constants::ClickType::NONE;
}

auto isClickableConfigurationValid(uint8_t clickableIndex) noexcept -> bool
{
    return clickableIndex < 5U;
}

auto setActuatorStateById(uint8_t actuatorId, bool state) noexcept -> bool
{
    switch (actuatorId)
    {
    case 1U:
    {
        return actuator0_ceilingActionSet(state);
    }
    case 2U:
    {
        return actuator1_worktopActionSet(state);
    }
    case 3U:
    {
        return actuator2_ambientActionSet(state);
    }
    case 4U:
    {
        return actuator3_door_strikeActionSet(state);
    }
    case 5U:
    {
        return actuator4_blind_upActionSet(state);
    }
    case 6U:
    {
        return actuator5_blind_downActionSet(state);
    }
    case 7U:
    {
        return actuator6_serviceActionSet(state);
    }
    default:
        return false;
    }
}

auto scanClickables(uint16_t elapsed_ms) noexcept -> uint8_t
{
    using constants::ClickResult;
    using namespace Debug;
    uint8_t scanResultFlags = 0U;

    {
        const auto button0_doorClickResult =
            button0_door.clickDetection<constants::clickDetection::makeFlags(true, true, true), 900U, 1600U>(elapsed_ms);
        switch (button0_doorClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 1U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (actuator0_ceilingActionToggle())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 1U, FPSTR(dStr::SPACE), FPSTR(dStr::LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (actuator0_ceilingActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator1_worktopActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator2_ambientActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::SUPER_LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 1U, FPSTR(dStr::SPACE), FPSTR(dStr::SUPER_LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (actuator0_ceilingActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator1_worktopActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator2_ambientActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator3_door_strikeActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator4_blind_upActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator5_blind_downActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto button1_worktopClickResult =
            button1_worktop.clickDetection<constants::clickDetection::makeFlags(true, true, true), 800U, 1600U>(elapsed_ms);
        switch (button1_worktopClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 2U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (actuator0_ceilingActionToggle(actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator1_worktopActionToggle(actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator2_ambientActionToggle(actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 2U, FPSTR(dStr::SPACE), FPSTR(dStr::LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (actuator2_ambientActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator0_ceilingActionSet(true, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator1_worktopActionSet(true, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::SUPER_LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 2U, FPSTR(dStr::SPACE), FPSTR(dStr::SUPER_LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (actuator0_ceilingActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator1_worktopActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator2_ambientActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator4_blind_upActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator5_blind_downActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto button2_strikeClickResult =
            button2_strike.clickDetection<constants::clickDetection::makeFlags(true, true, false), 800U, 1000U>(elapsed_ms);
        switch (button2_strikeClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 3U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (actuator3_door_strikeActionToggle())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 3U, FPSTR(dStr::SPACE), FPSTR(dStr::LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (BridgeSerial::isConnected())
            {
                const auto requestResult = NetworkClicks::request(2U, constants::ClickType::LONG);
                if (requestResult == NetworkClicks::RequestResult::Accepted)
                {
                    scanResultFlags |= CLICK_SCAN_NETWORK_PENDING;
                }
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto button3_blind_upClickResult =
            button3_blind_up.clickDetection<constants::clickDetection::makeFlags(true, true, false), 800U, 1000U>(elapsed_ms);
        switch (button3_blind_upClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 4U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (actuator4_blind_upActionToggle())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 4U, FPSTR(dStr::SPACE), FPSTR(dStr::LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (actuator4_blind_upActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator5_blind_downActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto button4_blind_downClickResult =
            button4_blind_down.clickDetection<constants::clickDetection::makeFlags(true, true, false), 800U, 1000U>(elapsed_ms);
        switch (button4_blind_downClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 5U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (actuator5_blind_downActionToggle())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 5U, FPSTR(dStr::SPACE), FPSTR(dStr::LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (actuator4_blind_upActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (actuator5_blind_downActionSet(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    return scanResultFlags;
}

auto checkPulseTimers(uint16_t elapsed_ms) noexcept -> bool
{
    if (activePulseActuators == 0U)
    {
        return false;
    }

    bool anyActuatorChangedState = false;
    if (pulseRemaining_ms[0U] != 0U)
    {
        if (pulseRemaining_ms[0U] <= elapsed_ms)
        {
            pulseRemaining_ms[0U] = 0U;
            --activePulseActuators;
            anyActuatorChangedState |= actuator3_door_strikeActionSet(false);
        }
        else
        {
            pulseRemaining_ms[0U] = static_cast<uint16_t>(pulseRemaining_ms[0U] - elapsed_ms);
        }
    }
    return anyActuatorChangedState;
}

auto checkAutoOffTimers(uint32_t now_ms) noexcept -> bool
{
    bool anyActuatorChangedState = false;
#if CONFIG_USE_COMPACT_ACTUATOR_SWITCH_TIMES
    anyActuatorChangedState |= Actuators::checkCompactAutoOffTimer(0U, 1U, actuator1_worktop, now_ms, 2700000UL);
#else
    anyActuatorChangedState |= actuator1_worktop.checkAutoOffTimerForIndex(1U, now_ms, 2700000UL);
#endif
    return anyActuatorChangedState;
}

auto applyPackedActuatorStateByte(uint8_t byteIndex, uint8_t packedByte) noexcept -> bool
{
    switch (byteIndex)
    {
    case 0U:
    {
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= actuator0_ceilingActionSet((packedByte & 1U) != 0U, actionNow);
        anyActuatorChangedState |= actuator1_worktopActionSet((packedByte & 2U) != 0U, actionNow);
        anyActuatorChangedState |= actuator2_ambientActionSet((packedByte & 4U) != 0U, actionNow);
        anyActuatorChangedState |= actuator3_door_strikeActionSet((packedByte & 8U) != 0U, actionNow);
        anyActuatorChangedState |= actuator4_blind_upActionSet((packedByte & 16U) != 0U, actionNow);
        anyActuatorChangedState |= actuator5_blind_downActionSet((packedByte & 32U) != 0U, actionNow);
        anyActuatorChangedState |= actuator6_serviceActionSet((packedByte & 64U) != 0U, actionNow);
        return anyActuatorChangedState;
    }
    default:
        return false;
    }
}

auto computeIndicatorState(uint8_t indicatorIndex) noexcept -> bool
{
    switch (indicatorIndex)
    {
    case 0U:
    {
        return actuator0_ceiling.getState();
    }
    case 1U:
    {
        return actuator0_ceiling.getState() || actuator1_worktop.getState() || actuator2_ambient.getState();
    }
    case 2U:
    {
        return actuator0_ceiling.getState() && actuator1_worktop.getState();
    }
    default:
        return false;
    }
}

void refreshIndicators() noexcept
{
    indicator0_ceiling_led.applyComputedState(actuator0_ceiling.getState());
    const bool indicator1_any_light_ledState = actuator0_ceiling.getState() || actuator1_worktop.getState() || actuator2_ambient.getState();
    indicator1_any_light_led.applyComputedState(indicator1_any_light_ledState);
    indicator2_cooking_led.applyComputedState(actuator0_ceiling.getState() && actuator1_worktop.getState());
}
}  // namespace lsh::core::static_config

void Configurator::configure()
{
    using namespace Debug;

    DP_CONTEXT();

    Actuators::packedActuatorStates[0U] = 4U;

#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    actuator0_ceiling.setIndex(0U);
    Actuators::actuators[0U] = &actuator0_ceiling;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    actuator1_worktop.setIndex(1U);
    Actuators::actuators[1U] = &actuator1_worktop;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    actuator2_ambient.setIndex(2U);
    Actuators::actuators[2U] = &actuator2_ambient;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    actuator3_door_strike.setIndex(3U);
    Actuators::actuators[3U] = &actuator3_door_strike;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    actuator4_blind_up.setIndex(4U);
    Actuators::actuators[4U] = &actuator4_blind_up;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    actuator5_blind_down.setIndex(5U);
    Actuators::actuators[5U] = &actuator5_blind_down;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    actuator6_service.setIndex(6U);
    Actuators::actuators[6U] = &actuator6_service;
#endif

#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    button0_door.setIndex(0U);
    Clickables::clickables[0U] = &button0_door;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    button1_worktop.setIndex(1U);
    Clickables::clickables[1U] = &button1_worktop;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    button2_strike.setIndex(2U);
    Clickables::clickables[2U] = &button2_strike;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    button3_blind_up.setIndex(3U);
    Clickables::clickables[3U] = &button3_blind_up;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    button4_blind_down.setIndex(4U);
    Clickables::clickables[4U] = &button4_blind_down;
#endif

#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    indicator0_ceiling_led.setIndex(0U);
    Indicators::indicators[0U] = &indicator0_ceiling_led;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    indicator1_any_light_led.setIndex(1U);
    Indicators::indicators[1U] = &indicator1_any_light_led;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    indicator2_cooking_led.setIndex(2U);
    Indicators::indicators[2U] = &indicator2_cooking_led;
#endif

    actuator6_service.setProtected(true);
}

#undef LSH_STATIC_CONFIG_READ_BYTE
#undef LSH_STATIC_CONFIG_PROGMEM

#endif  // LSH_GENERATED_LSH_CONFIGS_KITCHEN_STATIC_CONFIG_HPP_IMPLEMENTATION

#else
#error "kitchen_static_config.hpp must be included through a static-config pass macro."
#endif
