/**
 * @file    j1_config.hpp
 * @brief   Generated lsh-core static configuration. Edit the TOML source instead.
 */

// Generated by tools/generate_lsh_static_config.py from lsh_devices.toml. Do not edit by hand.

#ifndef LSH_GENERATED_LSH_CONFIGS_J1_CONFIG_HPP
#define LSH_GENERATED_LSH_CONFIGS_J1_CONFIG_HPP

#define LSH_HARDWARE_INCLUDE <Controllino.h>
#define LSH_DEVICE_NAME "j1"
#define LSH_STATIC_CONFIG_INCLUDE "lsh_configs/j1_static_config.hpp"
#define LSH_COM_SERIAL &Serial2
#define LSH_DEBUG_SERIAL &Serial

#endif  // LSH_GENERATED_LSH_CONFIGS_J1_CONFIG_HPP
