/**
 * @file    j1_static_config.hpp
 * @brief   Generated lsh-core static configuration. Edit the TOML source instead.
 */

// Generated by tools/generate_lsh_static_config.py from lsh_devices.toml. Do not edit by hand.

#if defined(LSH_STATIC_CONFIG_RESOURCE_PASS)

#ifndef LSH_GENERATED_LSH_CONFIGS_J1_STATIC_CONFIG_HPP_RESOURCE
#define LSH_GENERATED_LSH_CONFIGS_J1_STATIC_CONFIG_HPP_RESOURCE

#define LSH_STATIC_CONFIG_CLICKABLES 10
#define LSH_STATIC_CONFIG_ACTUATORS 9
#define LSH_STATIC_CONFIG_INDICATORS 1
#define LSH_STATIC_CONFIG_MAX_CLICKABLE_ID 11
#define LSH_STATIC_CONFIG_MAX_ACTUATOR_ID 10
#define LSH_STATIC_CONFIG_SHORT_CLICK_ACTUATOR_LINKS 10
#define LSH_STATIC_CONFIG_LONG_CLICK_ACTUATOR_LINKS 12
#define LSH_STATIC_CONFIG_SUPER_LONG_CLICK_ACTUATOR_LINKS 2
#define LSH_STATIC_CONFIG_INDICATOR_ACTUATOR_LINKS 1
#define LSH_STATIC_CONFIG_AUTO_OFF_ACTUATORS 6
#define LSH_STATIC_CONFIG_ACTIVE_NETWORK_CLICKS 0
#define LSH_STATIC_CONFIG_DISABLE_NETWORK_CLICKS 1

#endif  // LSH_GENERATED_LSH_CONFIGS_J1_STATIC_CONFIG_HPP_RESOURCE

#elif defined(LSH_STATIC_CONFIG_IMPLEMENTATION_PASS)

#ifndef LSH_GENERATED_LSH_CONFIGS_J1_STATIC_CONFIG_HPP_IMPLEMENTATION
#define LSH_GENERATED_LSH_CONFIGS_J1_STATIC_CONFIG_HPP_IMPLEMENTATION

#include "communication/bridge_serial.hpp"
#include "config/static_config.hpp"
#include "core/network_clicks.hpp"
#include "device/actuator_manager.hpp"
#include "device/clickable_manager.hpp"
#include "device/indicator_manager.hpp"
#include "lsh_user_macros.hpp"
#include "util/constants/click_detection.hpp"
#include "util/constants/click_results.hpp"
#include "util/constants/click_types.hpp"
#include "util/constants/timing.hpp"
#include "util/debug/debug.hpp"
#include "util/time_keeper.hpp"

#if defined(__AVR__)
#include <avr/pgmspace.h>
#define LSH_STATIC_CONFIG_PROGMEM PROGMEM
#define LSH_STATIC_CONFIG_READ_BYTE(address) pgm_read_byte(address)
#else
#define LSH_STATIC_CONFIG_PROGMEM
#define LSH_STATIC_CONFIG_READ_BYTE(address) (*(address))
#endif

namespace
{
// clang-format off
const uint8_t DETAILS_JSON_PAYLOAD[] LSH_STATIC_CONFIG_PROGMEM = {
    0x7BU, 0x22U, 0x70U, 0x22U, 0x3AU, 0x31U, 0x2CU, 0x22U, 0x76U, 0x22U, 0x3AU, 0x33U,
    0x2CU, 0x22U, 0x6EU, 0x22U, 0x3AU, 0x22U, 0x6AU, 0x31U, 0x22U, 0x2CU, 0x22U, 0x61U,
    0x22U, 0x3AU, 0x5BU, 0x31U, 0x2CU, 0x32U, 0x2CU, 0x33U, 0x2CU, 0x34U, 0x2CU, 0x35U,
    0x2CU, 0x36U, 0x2CU, 0x37U, 0x2CU, 0x38U, 0x2CU, 0x31U, 0x30U, 0x5DU, 0x2CU, 0x22U,
    0x62U, 0x22U, 0x3AU, 0x5BU, 0x31U, 0x2CU, 0x32U, 0x2CU, 0x33U, 0x2CU, 0x34U, 0x2CU,
    0x35U, 0x2CU, 0x36U, 0x2CU, 0x37U, 0x2CU, 0x38U, 0x2CU, 0x31U, 0x30U, 0x2CU, 0x31U,
    0x31U, 0x5DU, 0x7DU, 0x0AU
};

const uint8_t DETAILS_MSGPACK_PAYLOAD[] LSH_STATIC_CONFIG_PROGMEM = {
    0xC0U, 0x85U, 0xA1U, 0x70U, 0x01U, 0xA1U, 0x76U, 0x03U, 0xA1U, 0x6EU, 0xA2U, 0x6AU,
    0x31U, 0xA1U, 0x61U, 0x99U, 0x01U, 0x02U, 0x03U, 0x04U, 0x05U, 0x06U, 0x07U, 0x08U,
    0x0AU, 0xA1U, 0x62U, 0x9AU, 0x01U, 0x02U, 0x03U, 0x04U, 0x05U, 0x06U, 0x07U, 0x08U,
    0x0AU, 0x0BU, 0xC0U
};
// clang-format on

constexpr uint16_t LSH_STATIC_CONFIG_UNROLLED_PAYLOAD_LIMIT = 128U;

template <uint16_t ByteIndex, uint16_t PayloadSize> struct GeneratedPayloadByteWriter
{
    static auto write(const uint8_t (&payload)[PayloadSize]) noexcept -> bool
    {
        return CONFIG_COM_SERIAL->HardwareSerial::write(LSH_STATIC_CONFIG_READ_BYTE(&payload[ByteIndex])) == 1U &&
               GeneratedPayloadByteWriter<static_cast<uint16_t>(ByteIndex + 1U), PayloadSize>::write(payload);
    }
};

template <uint16_t PayloadSize> struct GeneratedPayloadByteWriter<PayloadSize, PayloadSize>
{
    static auto write(const uint8_t (&payload)[PayloadSize]) noexcept -> bool
    {
        static_cast<void>(payload);
        return true;
    }
};

template <uint16_t PayloadSize> auto writeGeneratedPayloadLoop(const uint8_t (&payload)[PayloadSize]) noexcept -> bool
{
    for (uint16_t byteIndex = 0U; byteIndex < PayloadSize; ++byteIndex)
    {
        if (CONFIG_COM_SERIAL->HardwareSerial::write(LSH_STATIC_CONFIG_READ_BYTE(&payload[byteIndex])) != 1U)
        {
            return false;
        }
    }
    return true;
}

template <uint16_t PayloadSize> auto writeGeneratedPayload(const uint8_t (&payload)[PayloadSize]) noexcept -> bool
{
    static_assert(PayloadSize > 0U, "Generated static payloads must not be empty.");
    if constexpr (PayloadSize <= LSH_STATIC_CONFIG_UNROLLED_PAYLOAD_LIMIT)
    {
        return GeneratedPayloadByteWriter<0U, PayloadSize>::write(payload);
    }
    return writeGeneratedPayloadLoop(payload);
}

LSH_ACTUATOR(rel0, CONTROLLINO_R0);
LSH_ACTUATOR(rel1, CONTROLLINO_R1);
LSH_ACTUATOR(rel2, CONTROLLINO_R2);
LSH_ACTUATOR(rel3, CONTROLLINO_R3);
LSH_ACTUATOR(rel4, CONTROLLINO_R4);
LSH_ACTUATOR(rel5, CONTROLLINO_R5);
LSH_ACTUATOR(rel6, CONTROLLINO_R6);
LSH_ACTUATOR(rel7, CONTROLLINO_R7);
LSH_ACTUATOR(rel9, CONTROLLINO_R9);

LSH_BUTTON(btn0, CONTROLLINO_A0);
LSH_BUTTON(btn1, CONTROLLINO_A1);
LSH_BUTTON(btn2, CONTROLLINO_A2);
LSH_BUTTON(btn3, CONTROLLINO_A3);
LSH_BUTTON(btn4, CONTROLLINO_A4);
LSH_BUTTON(btn5, CONTROLLINO_A5);
LSH_BUTTON(btn6, CONTROLLINO_A6);
LSH_BUTTON(btn7, CONTROLLINO_A7);
LSH_BUTTON(btn9, CONTROLLINO_A9);
LSH_BUTTON(btn10, CONTROLLINO_IN0);

LSH_INDICATOR(light9, CONTROLLINO_D9);
}  // namespace

namespace lsh::core::static_config
{
auto getActuatorId(uint8_t actuatorIndex) noexcept -> uint8_t
{
    if (actuatorIndex < 8U)
    {
        return static_cast<uint8_t>(actuatorIndex + 1U);
    }

    return actuatorIndex == 8U ? 10U : 0U;
}

auto getClickableId(uint8_t clickableIndex) noexcept -> uint8_t
{
    if (clickableIndex < 8U)
    {
        return static_cast<uint8_t>(clickableIndex + 1U);
    }

    return clickableIndex >= 8U && clickableIndex <= 9U ? static_cast<uint8_t>(clickableIndex + 2U) : 0U;
}

auto getActuatorIndexById(uint8_t actuatorId) noexcept -> uint8_t
{
    if (actuatorId >= 1U && actuatorId <= 8U)
    {
        return static_cast<uint8_t>(actuatorId - 1U);
    }

    return actuatorId == 10U ? 8U : UINT8_MAX;
}

auto getClickableIndexById(uint8_t clickableId) noexcept -> uint8_t
{
    if (clickableId >= 1U && clickableId <= 8U)
    {
        return static_cast<uint8_t>(clickableId - 1U);
    }

    return clickableId >= 10U && clickableId <= 11U ? static_cast<uint8_t>(clickableId - 2U) : UINT8_MAX;
}

auto getAutoOffActuatorIndex(uint8_t autoOffIndex) noexcept -> uint8_t
{
    if (autoOffIndex < 4U)
    {
        return autoOffIndex;
    }

    return autoOffIndex >= 4U && autoOffIndex <= 5U ? static_cast<uint8_t>(autoOffIndex + 3U) : UINT8_MAX;
}

auto getAutoOffIndexByActuatorIndex(uint8_t actuatorIndex) noexcept -> uint8_t
{
    if (actuatorIndex < 4U)
    {
        return actuatorIndex;
    }

    return actuatorIndex >= 7U && actuatorIndex <= 8U ? static_cast<uint8_t>(actuatorIndex - 3U) : UINT8_MAX;
}

auto getAutoOffTimer(uint8_t actuatorIndex) noexcept -> uint32_t
{
    if (actuatorIndex == 0U)
    {
        return 600000UL;
    }

    if ((actuatorIndex >= 1U && actuatorIndex <= 2U) || (actuatorIndex == 7U))
    {
        return 3600000UL;
    }

    if (actuatorIndex == 3U)
    {
        return 900000UL;
    }

    return actuatorIndex == 8U ? 1800000UL : 0UL;
}

auto getIndicatorActuatorLinkCount(uint8_t indicatorIndex) noexcept -> uint8_t
{
    if (indicatorIndex == 0U)
    {
        return 1U;
    }

    return 0U;
}

auto writeDetailsPayload() noexcept -> bool
{
#ifdef CONFIG_MSG_PACK
    return writeGeneratedPayload(DETAILS_MSGPACK_PAYLOAD);
#else
    return writeGeneratedPayload(DETAILS_JSON_PAYLOAD);
#endif
}

auto runShortClick(uint8_t clickableIndex) noexcept -> bool
{
    switch (clickableIndex)
    {
    case 0U:
    {
        return rel0.toggleStateStatic<0U>();
    }
    case 1U:
    {
        return rel1.toggleStateStatic<1U>();
    }
    case 2U:
    {
        return rel2.toggleStateStatic<2U>();
    }
    case 3U:
    {
        return rel3.toggleStateStatic<3U>();
    }
    case 4U:
    {
        return rel4.toggleStateStatic<4U>();
    }
    case 5U:
    {
        return rel5.toggleStateStatic<5U>();
    }
    case 6U:
    {
        return rel6.toggleStateStatic<6U>();
    }
    case 7U:
    {
        return rel7.toggleStateStatic<7U>();
    }
    case 8U:
    {
        return rel9.toggleStateStatic<8U>();
    }
    case 9U:
    {
        return rel0.toggleStateStatic<0U>();
    }
    default:
        return false;
    }
}

auto runLongClick(uint8_t clickableIndex) noexcept -> bool
{
    switch (clickableIndex)
    {
    case 1U:
    {
        const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel1.getState()) + static_cast<uint8_t>(rel2.getState());
        const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel1.setStateStatic<1U>(stateToSet, actionNow);
        anyActuatorChangedState |= rel2.setStateStatic<2U>(stateToSet, actionNow);
        return anyActuatorChangedState;
    }
    case 2U:
    {
        const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel2.getState()) + static_cast<uint8_t>(rel1.getState());
        const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel2.setStateStatic<2U>(stateToSet, actionNow);
        anyActuatorChangedState |= rel1.setStateStatic<1U>(stateToSet, actionNow);
        return anyActuatorChangedState;
    }
    case 4U:
    {
        const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel4.getState()) + static_cast<uint8_t>(rel5.getState());
        const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel4.setStateStatic<4U>(stateToSet, actionNow);
        anyActuatorChangedState |= rel5.setStateStatic<5U>(stateToSet, actionNow);
        return anyActuatorChangedState;
    }
    case 5U:
    {
        const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel5.getState()) + static_cast<uint8_t>(rel4.getState());
        const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel5.setStateStatic<5U>(stateToSet, actionNow);
        anyActuatorChangedState |= rel4.setStateStatic<4U>(stateToSet, actionNow);
        return anyActuatorChangedState;
    }
    case 6U:
    {
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel6.setStateStatic<6U>(false, actionNow);
        anyActuatorChangedState |= rel4.setStateStatic<4U>(false, actionNow);
        anyActuatorChangedState |= rel5.setStateStatic<5U>(false, actionNow);
        return anyActuatorChangedState;
    }
    case 7U:
    {
        const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel7.getState());
        const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 1U);
        return rel7.setStateStatic<7U>(stateToSet);
    }
    default:
        return false;
    }
}

auto turnOffAllActuators() noexcept -> bool
{
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
    const uint32_t actionNow = timeKeeper::getTime();
#else
    constexpr uint32_t actionNow = 0U;
#endif
    bool anyActuatorChangedState = false;
    anyActuatorChangedState |= rel0.setStateStatic<0U>(false, actionNow);
    anyActuatorChangedState |= rel1.setStateStatic<1U>(false, actionNow);
    anyActuatorChangedState |= rel2.setStateStatic<2U>(false, actionNow);
    anyActuatorChangedState |= rel3.setStateStatic<3U>(false, actionNow);
    anyActuatorChangedState |= rel4.setStateStatic<4U>(false, actionNow);
    anyActuatorChangedState |= rel5.setStateStatic<5U>(false, actionNow);
    anyActuatorChangedState |= rel6.setStateStatic<6U>(false, actionNow);
    anyActuatorChangedState |= rel7.setStateStatic<7U>(false, actionNow);
    anyActuatorChangedState |= rel9.setStateStatic<8U>(false, actionNow);
    return anyActuatorChangedState;
}

auto turnOffUnprotectedActuators() noexcept -> bool
{
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
    const uint32_t actionNow = timeKeeper::getTime();
#else
    constexpr uint32_t actionNow = 0U;
#endif
    bool anyActuatorChangedState = false;
    anyActuatorChangedState |= rel0.setStateStatic<0U>(false, actionNow);
    anyActuatorChangedState |= rel1.setStateStatic<1U>(false, actionNow);
    anyActuatorChangedState |= rel2.setStateStatic<2U>(false, actionNow);
    anyActuatorChangedState |= rel3.setStateStatic<3U>(false, actionNow);
    anyActuatorChangedState |= rel4.setStateStatic<4U>(false, actionNow);
    anyActuatorChangedState |= rel5.setStateStatic<5U>(false, actionNow);
    anyActuatorChangedState |= rel6.setStateStatic<6U>(false, actionNow);
    anyActuatorChangedState |= rel7.setStateStatic<7U>(false, actionNow);
    anyActuatorChangedState |= rel9.setStateStatic<8U>(false, actionNow);
    return anyActuatorChangedState;
}

auto runSuperLongClick(uint8_t clickableIndex) noexcept -> bool
{
    switch (clickableIndex)
    {
    case 7U:
    {
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel1.setStateStatic<1U>(false, actionNow);
        anyActuatorChangedState |= rel2.setStateStatic<2U>(false, actionNow);
        return anyActuatorChangedState;
    }
    case 9U:
    {
        return turnOffUnprotectedActuators();
    }
    default:
        return false;
    }
}

auto runClick(uint8_t clickableIndex, constants::ClickType clickType) noexcept -> bool
{
    switch (clickType)
    {
    case constants::ClickType::SHORT:
        return runShortClick(clickableIndex);
    case constants::ClickType::LONG:
        return runLongClick(clickableIndex);
    case constants::ClickType::SUPER_LONG:
        return runSuperLongClick(clickableIndex);
    default:
        return false;
    }
}

auto runNetworkClickFallback(uint8_t clickableIndex, constants::ClickType clickType) noexcept -> bool
{
    static_cast<void>(clickableIndex);
    static_cast<void>(clickType);
    return false;
}

auto getNetworkClickSlotCount(uint8_t clickableIndex) noexcept -> uint8_t
{
    static_cast<void>(clickableIndex);
    return 0U;
}

auto getNetworkClickSlotIndex(uint8_t clickableIndex, constants::ClickType clickType) noexcept -> uint8_t
{
    static_cast<void>(clickableIndex);
    static_cast<void>(clickType);
    return UINT8_MAX;
}

auto getNetworkClickClickableIndex(uint8_t slotIndex) noexcept -> uint8_t
{
    static_cast<void>(slotIndex);
    return UINT8_MAX;
}

auto getNetworkClickType(uint8_t slotIndex) noexcept -> constants::ClickType
{
    static_cast<void>(slotIndex);
    return constants::ClickType::NONE;
}

auto isClickableConfigurationValid(uint8_t clickableIndex) noexcept -> bool
{
    return clickableIndex < 10U;
}

auto setActuatorStateById(uint8_t actuatorId, bool state) noexcept -> bool
{
    switch (actuatorId)
    {
    case 1U:
    {
        return rel0.setStateStatic<0U>(state);
    }
    case 2U:
    {
        return rel1.setStateStatic<1U>(state);
    }
    case 3U:
    {
        return rel2.setStateStatic<2U>(state);
    }
    case 4U:
    {
        return rel3.setStateStatic<3U>(state);
    }
    case 5U:
    {
        return rel4.setStateStatic<4U>(state);
    }
    case 6U:
    {
        return rel5.setStateStatic<5U>(state);
    }
    case 7U:
    {
        return rel6.setStateStatic<6U>(state);
    }
    case 8U:
    {
        return rel7.setStateStatic<7U>(state);
    }
    case 10U:
    {
        return rel9.setStateStatic<8U>(state);
    }
    default:
        return false;
    }
}

auto scanClickables(uint16_t elapsed_ms) noexcept -> uint8_t
{
    using constants::ClickResult;
    using namespace Debug;
    uint8_t scanResultFlags = 0U;

    {
        const auto btn0ClickResult = btn0.clickDetection<constants::clickDetection::makeFlags(true, false, false), 400U, 1000U>(elapsed_ms);
        switch (btn0ClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 1U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (rel0.toggleStateStatic<0U>())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto btn1ClickResult = btn1.clickDetection<constants::clickDetection::makeFlags(true, true, false), 400U, 1000U>(elapsed_ms);
        switch (btn1ClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 2U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (rel1.toggleStateStatic<1U>())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 2U, FPSTR(dStr::SPACE), FPSTR(dStr::LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel1.getState()) + static_cast<uint8_t>(rel2.getState());
            const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (rel1.setStateStatic<1U>(stateToSet, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel2.setStateStatic<2U>(stateToSet, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto btn2ClickResult = btn2.clickDetection<constants::clickDetection::makeFlags(true, true, false), 400U, 1000U>(elapsed_ms);
        switch (btn2ClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 3U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (rel2.toggleStateStatic<2U>())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 3U, FPSTR(dStr::SPACE), FPSTR(dStr::LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel2.getState()) + static_cast<uint8_t>(rel1.getState());
            const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (rel2.setStateStatic<2U>(stateToSet, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel1.setStateStatic<1U>(stateToSet, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto btn3ClickResult = btn3.clickDetection<constants::clickDetection::makeFlags(true, false, false), 400U, 1000U>(elapsed_ms);
        switch (btn3ClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 4U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (rel3.toggleStateStatic<3U>())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto btn4ClickResult = btn4.clickDetection<constants::clickDetection::makeFlags(true, true, false), 400U, 1000U>(elapsed_ms);
        switch (btn4ClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 5U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (rel4.toggleStateStatic<4U>())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 5U, FPSTR(dStr::SPACE), FPSTR(dStr::LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel4.getState()) + static_cast<uint8_t>(rel5.getState());
            const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (rel4.setStateStatic<4U>(stateToSet, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel5.setStateStatic<5U>(stateToSet, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto btn5ClickResult = btn5.clickDetection<constants::clickDetection::makeFlags(true, true, false), 400U, 1000U>(elapsed_ms);
        switch (btn5ClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 6U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (rel5.toggleStateStatic<5U>())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 6U, FPSTR(dStr::SPACE), FPSTR(dStr::LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel5.getState()) + static_cast<uint8_t>(rel4.getState());
            const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (rel5.setStateStatic<5U>(stateToSet, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel4.setStateStatic<4U>(stateToSet, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto btn6ClickResult = btn6.clickDetection<constants::clickDetection::makeFlags(true, true, false), 400U, 1000U>(elapsed_ms);
        switch (btn6ClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 7U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (rel6.toggleStateStatic<6U>())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 7U, FPSTR(dStr::SPACE), FPSTR(dStr::LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (rel6.setStateStatic<6U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel4.setStateStatic<4U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel5.setStateStatic<5U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto btn7ClickResult = btn7.clickDetection<constants::clickDetection::makeFlags(true, true, true), 900U, 1000U>(elapsed_ms);
        switch (btn7ClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 8U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (rel7.toggleStateStatic<7U>())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 8U, FPSTR(dStr::SPACE), FPSTR(dStr::LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel7.getState());
            const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 1U);
            if (rel7.setStateStatic<7U>(stateToSet))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::SUPER_LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 8U, FPSTR(dStr::SPACE), FPSTR(dStr::SUPER_LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (rel1.setStateStatic<1U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel2.setStateStatic<2U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto btn9ClickResult = btn9.clickDetection<constants::clickDetection::makeFlags(true, false, false), 400U, 1000U>(elapsed_ms);
        switch (btn9ClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 10U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (rel9.toggleStateStatic<8U>())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    {
        const auto btn10ClickResult =
            btn10.clickDetection<constants::clickDetection::makeFlags(true, false, true), 400U, 1000U>(elapsed_ms);
        switch (btn10ClickResult)
        {
        case ClickResult::SHORT_CLICK:
        case ClickResult::SHORT_CLICK_QUICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 11U, FPSTR(dStr::SPACE), FPSTR(dStr::SHORT), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
            if (rel0.toggleStateStatic<0U>())
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        case ClickResult::SUPER_LONG_CLICK:
        {
            DPL(FPSTR(dStr::CLICKABLE), FPSTR(dStr::SPACE), 11U, FPSTR(dStr::SPACE), FPSTR(dStr::SUPER_LONG), FPSTR(dStr::SPACE),
                FPSTR(dStr::CLICKED));
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
            const uint32_t actionNow = timeKeeper::getTime();
#else
            constexpr uint32_t actionNow = 0U;
#endif
            if (rel0.setStateStatic<0U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel1.setStateStatic<1U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel2.setStateStatic<2U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel3.setStateStatic<3U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel4.setStateStatic<4U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel5.setStateStatic<5U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel6.setStateStatic<6U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel7.setStateStatic<7U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
            if (rel9.setStateStatic<8U>(false, actionNow))
            {
                scanResultFlags |= CLICK_SCAN_STATE_CHANGED;
            }
        }
        break;

        default:
            break;
        }
    }

    return scanResultFlags;
}

auto checkAutoOffTimers(uint32_t now_ms) noexcept -> bool
{
    bool anyActuatorChangedState = false;
#if CONFIG_USE_COMPACT_ACTUATOR_SWITCH_TIMES
    anyActuatorChangedState |= Actuators::checkCompactAutoOffTimer(0U, 0U, rel0, now_ms, 600000UL);
#else
    anyActuatorChangedState |= rel0.checkAutoOffTimerForIndex(0U, now_ms, 600000UL);
#endif
#if CONFIG_USE_COMPACT_ACTUATOR_SWITCH_TIMES
    anyActuatorChangedState |= Actuators::checkCompactAutoOffTimer(1U, 1U, rel1, now_ms, 3600000UL);
#else
    anyActuatorChangedState |= rel1.checkAutoOffTimerForIndex(1U, now_ms, 3600000UL);
#endif
#if CONFIG_USE_COMPACT_ACTUATOR_SWITCH_TIMES
    anyActuatorChangedState |= Actuators::checkCompactAutoOffTimer(2U, 2U, rel2, now_ms, 3600000UL);
#else
    anyActuatorChangedState |= rel2.checkAutoOffTimerForIndex(2U, now_ms, 3600000UL);
#endif
#if CONFIG_USE_COMPACT_ACTUATOR_SWITCH_TIMES
    anyActuatorChangedState |= Actuators::checkCompactAutoOffTimer(3U, 3U, rel3, now_ms, 900000UL);
#else
    anyActuatorChangedState |= rel3.checkAutoOffTimerForIndex(3U, now_ms, 900000UL);
#endif
#if CONFIG_USE_COMPACT_ACTUATOR_SWITCH_TIMES
    anyActuatorChangedState |= Actuators::checkCompactAutoOffTimer(4U, 7U, rel7, now_ms, 3600000UL);
#else
    anyActuatorChangedState |= rel7.checkAutoOffTimerForIndex(7U, now_ms, 3600000UL);
#endif
#if CONFIG_USE_COMPACT_ACTUATOR_SWITCH_TIMES
    anyActuatorChangedState |= Actuators::checkCompactAutoOffTimer(5U, 8U, rel9, now_ms, 1800000UL);
#else
    anyActuatorChangedState |= rel9.checkAutoOffTimerForIndex(8U, now_ms, 1800000UL);
#endif
    return anyActuatorChangedState;
}

auto applyPackedActuatorStateByte(uint8_t byteIndex, uint8_t packedByte) noexcept -> bool
{
    switch (byteIndex)
    {
    case 0U:
    {
#if LSH_CORE_ACTUATOR_NEEDS_SWITCH_TIMESTAMP
        const uint32_t actionNow = timeKeeper::getTime();
#else
        constexpr uint32_t actionNow = 0U;
#endif
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel0.setStateStatic<0U>((packedByte & 1U) != 0U, actionNow);
        anyActuatorChangedState |= rel1.setStateStatic<1U>((packedByte & 2U) != 0U, actionNow);
        anyActuatorChangedState |= rel2.setStateStatic<2U>((packedByte & 4U) != 0U, actionNow);
        anyActuatorChangedState |= rel3.setStateStatic<3U>((packedByte & 8U) != 0U, actionNow);
        anyActuatorChangedState |= rel4.setStateStatic<4U>((packedByte & 16U) != 0U, actionNow);
        anyActuatorChangedState |= rel5.setStateStatic<5U>((packedByte & 32U) != 0U, actionNow);
        anyActuatorChangedState |= rel6.setStateStatic<6U>((packedByte & 64U) != 0U, actionNow);
        anyActuatorChangedState |= rel7.setStateStatic<7U>((packedByte & 128U) != 0U, actionNow);
        return anyActuatorChangedState;
    }
    case 1U:
    {
        return rel9.setStateStatic<8U>((packedByte & 1U) != 0U);
    }
    default:
        return false;
    }
}

auto computeIndicatorState(uint8_t indicatorIndex) noexcept -> bool
{
    switch (indicatorIndex)
    {
    case 0U:
    {
        return rel9.getState();
    }
    default:
        return false;
    }
}

void refreshIndicators() noexcept
{
    light9.applyComputedState(rel9.getState());
}
}  // namespace lsh::core::static_config

void Configurator::configure()
{
    using namespace Debug;

    DP_CONTEXT();

    Actuators::packedActuatorStates[0U] = 0U;
    Actuators::packedActuatorStates[1U] = 0U;

#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    rel0.setIndex(0U);
    Actuators::actuators[0U] = &rel0;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    rel1.setIndex(1U);
    Actuators::actuators[1U] = &rel1;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    rel2.setIndex(2U);
    Actuators::actuators[2U] = &rel2;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    rel3.setIndex(3U);
    Actuators::actuators[3U] = &rel3;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    rel4.setIndex(4U);
    Actuators::actuators[4U] = &rel4;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    rel5.setIndex(5U);
    Actuators::actuators[5U] = &rel5;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    rel6.setIndex(6U);
    Actuators::actuators[6U] = &rel6;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    rel7.setIndex(7U);
    Actuators::actuators[7U] = &rel7;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    rel9.setIndex(8U);
    Actuators::actuators[8U] = &rel9;
#endif

#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    btn0.setIndex(0U);
    Clickables::clickables[0U] = &btn0;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    btn1.setIndex(1U);
    Clickables::clickables[1U] = &btn1;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    btn2.setIndex(2U);
    Clickables::clickables[2U] = &btn2;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    btn3.setIndex(3U);
    Clickables::clickables[3U] = &btn3;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    btn4.setIndex(4U);
    Clickables::clickables[4U] = &btn4;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    btn5.setIndex(5U);
    Clickables::clickables[5U] = &btn5;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    btn6.setIndex(6U);
    Clickables::clickables[6U] = &btn6;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    btn7.setIndex(7U);
    Clickables::clickables[7U] = &btn7;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    btn9.setIndex(8U);
    Clickables::clickables[8U] = &btn9;
#endif
#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    btn10.setIndex(9U);
    Clickables::clickables[9U] = &btn10;
#endif

#if defined(LSH_DEBUG) || defined(LSH_STATIC_CONFIG_RUNTIME_CHECKS)
    light9.setIndex(0U);
    Indicators::indicators[0U] = &light9;
#endif
}

#undef LSH_STATIC_CONFIG_READ_BYTE
#undef LSH_STATIC_CONFIG_PROGMEM

#endif  // LSH_GENERATED_LSH_CONFIGS_J1_STATIC_CONFIG_HPP_IMPLEMENTATION

#else
#error "j1_static_config.hpp must be included through a static-config pass macro."
#endif
