/**
 * @file    j2_static_config.hpp
 * @brief   Generated lsh-core static configuration. Edit the TOML source instead.
 */

// Generated by tools/generate_lsh_static_config.py from lsh_devices.toml. Do not edit by hand.

#if defined(LSH_STATIC_CONFIG_RESOURCE_PASS)

#ifndef LSH_GENERATED_LSH_CONFIGS_J2_STATIC_CONFIG_HPP_RESOURCE
#define LSH_GENERATED_LSH_CONFIGS_J2_STATIC_CONFIG_HPP_RESOURCE

#define LSH_STATIC_CONFIG_CLICKABLES 10
#define LSH_STATIC_CONFIG_ACTUATORS 8
#define LSH_STATIC_CONFIG_INDICATORS 3
#define LSH_STATIC_CONFIG_MAX_CLICKABLE_ID 12
#define LSH_STATIC_CONFIG_MAX_ACTUATOR_ID 10
#define LSH_STATIC_CONFIG_SHORT_CLICK_ACTUATOR_LINKS 10
#define LSH_STATIC_CONFIG_LONG_CLICK_ACTUATOR_LINKS 12
#define LSH_STATIC_CONFIG_SUPER_LONG_CLICK_ACTUATOR_LINKS 0
#define LSH_STATIC_CONFIG_INDICATOR_ACTUATOR_LINKS 3
#define LSH_STATIC_CONFIG_CLICKABLE_TIMING_OVERRIDES 0
#define LSH_STATIC_CONFIG_AUTO_OFF_ACTUATORS 2
#define LSH_STATIC_CONFIG_ACTIVE_NETWORK_CLICKS 2
#define LSH_STATIC_CONFIG_DISABLE_NETWORK_CLICKS 0

#endif  // LSH_GENERATED_LSH_CONFIGS_J2_STATIC_CONFIG_HPP_RESOURCE

#elif defined(LSH_STATIC_CONFIG_IMPLEMENTATION_PASS)

#ifndef LSH_GENERATED_LSH_CONFIGS_J2_STATIC_CONFIG_HPP_IMPLEMENTATION
#define LSH_GENERATED_LSH_CONFIGS_J2_STATIC_CONFIG_HPP_IMPLEMENTATION

#include "device/actuator_manager.hpp"
#include "device/clickable_manager.hpp"
#include "device/indicator_manager.hpp"
#include "lsh_user_macros.hpp"
#include "util/constants/timing.hpp"

#if defined(__AVR__)
#include <avr/pgmspace.h>
#define LSH_STATIC_CONFIG_PROGMEM PROGMEM
#define LSH_STATIC_CONFIG_READ_BYTE(address) pgm_read_byte(address)
#else
#define LSH_STATIC_CONFIG_PROGMEM
#define LSH_STATIC_CONFIG_READ_BYTE(address) (*(address))
#endif

namespace
{
// clang-format off
const uint8_t DETAILS_JSON_PAYLOAD[] LSH_STATIC_CONFIG_PROGMEM = {
    0x7BU, 0x22U, 0x70U, 0x22U, 0x3AU, 0x31U, 0x2CU, 0x22U, 0x76U, 0x22U, 0x3AU, 0x33U,
    0x2CU, 0x22U, 0x6EU, 0x22U, 0x3AU, 0x22U, 0x6AU, 0x32U, 0x22U, 0x2CU, 0x22U, 0x61U,
    0x22U, 0x3AU, 0x5BU, 0x31U, 0x2CU, 0x32U, 0x2CU, 0x33U, 0x2CU, 0x34U, 0x2CU, 0x37U,
    0x2CU, 0x38U, 0x2CU, 0x39U, 0x2CU, 0x31U, 0x30U, 0x5DU, 0x2CU, 0x22U, 0x62U, 0x22U,
    0x3AU, 0x5BU, 0x31U, 0x2CU, 0x32U, 0x2CU, 0x33U, 0x2CU, 0x34U, 0x2CU, 0x37U, 0x2CU,
    0x38U, 0x2CU, 0x39U, 0x2CU, 0x31U, 0x30U, 0x2CU, 0x31U, 0x31U, 0x2CU, 0x31U, 0x32U,
    0x5DU, 0x7DU, 0x0AU
};

const uint8_t DETAILS_MSGPACK_PAYLOAD[] LSH_STATIC_CONFIG_PROGMEM = {
    0xC0U, 0x85U, 0xA1U, 0x70U, 0x01U, 0xA1U, 0x76U, 0x03U, 0xA1U, 0x6EU, 0xA2U, 0x6AU,
    0x32U, 0xA1U, 0x61U, 0x98U, 0x01U, 0x02U, 0x03U, 0x04U, 0x07U, 0x08U, 0x09U, 0x0AU,
    0xA1U, 0x62U, 0x9AU, 0x01U, 0x02U, 0x03U, 0x04U, 0x07U, 0x08U, 0x09U, 0x0AU, 0x0BU,
    0x0CU, 0xC0U
};
// clang-format on

template <uint16_t PayloadSize> auto writeGeneratedPayload(const uint8_t (&payload)[PayloadSize]) noexcept -> bool
{
    for (uint16_t byteIndex = 0U; byteIndex < PayloadSize; ++byteIndex)
    {
        if (CONFIG_COM_SERIAL->HardwareSerial::write(LSH_STATIC_CONFIG_READ_BYTE(&payload[byteIndex])) != 1U)
        {
            return false;
        }
    }
    return PayloadSize != 0U;
}

LSH_ACTUATOR(rel0, CONTROLLINO_R0);
LSH_ACTUATOR(rel1, CONTROLLINO_R1);
LSH_ACTUATOR(rel2, CONTROLLINO_R2);
LSH_ACTUATOR(rel3, CONTROLLINO_R3);
LSH_ACTUATOR(rel6, CONTROLLINO_R6);
LSH_ACTUATOR(rel7, CONTROLLINO_R7);
LSH_ACTUATOR(rel8, CONTROLLINO_R8);
LSH_ACTUATOR(rel9, CONTROLLINO_R9);

LSH_BUTTON(btn0, CONTROLLINO_A0);
LSH_BUTTON(btn1, CONTROLLINO_A1);
LSH_BUTTON(btn2, CONTROLLINO_A2);
LSH_BUTTON(btn3, CONTROLLINO_A3);
LSH_BUTTON(btn6, CONTROLLINO_A6);
LSH_BUTTON(btn7, CONTROLLINO_A7);
LSH_BUTTON(btn8, CONTROLLINO_A8);
LSH_BUTTON(btn9, CONTROLLINO_A9);
LSH_BUTTON(btn10, CONTROLLINO_IN0);
LSH_BUTTON(btn11, CONTROLLINO_IN1);

LSH_INDICATOR(light6, CONTROLLINO_D6);
LSH_INDICATOR(light7, CONTROLLINO_D7);
LSH_INDICATOR(light8, CONTROLLINO_D8);
}  // namespace

namespace lsh::core::static_config
{
auto getActuatorId(uint8_t actuatorIndex) noexcept -> uint8_t
{
    if (actuatorIndex < 4U)
    {
        return static_cast<uint8_t>(actuatorIndex + 1U);
    }

    return actuatorIndex >= 4U && actuatorIndex <= 7U ? static_cast<uint8_t>(actuatorIndex + 3U) : 0U;
}

auto getClickableId(uint8_t clickableIndex) noexcept -> uint8_t
{
    if (clickableIndex < 4U)
    {
        return static_cast<uint8_t>(clickableIndex + 1U);
    }

    return clickableIndex >= 4U && clickableIndex <= 9U ? static_cast<uint8_t>(clickableIndex + 3U) : 0U;
}

auto getActuatorIndexById(uint8_t actuatorId) noexcept -> uint8_t
{
    if (actuatorId >= 1U && actuatorId <= 4U)
    {
        return static_cast<uint8_t>(actuatorId - 1U);
    }

    return actuatorId >= 7U && actuatorId <= 10U ? static_cast<uint8_t>(actuatorId - 3U) : UINT8_MAX;
}

auto getClickableIndexById(uint8_t clickableId) noexcept -> uint8_t
{
    if (clickableId >= 1U && clickableId <= 4U)
    {
        return static_cast<uint8_t>(clickableId - 1U);
    }

    return clickableId >= 7U && clickableId <= 12U ? static_cast<uint8_t>(clickableId - 3U) : UINT8_MAX;
}

auto getAutoOffActuatorIndex(uint8_t autoOffIndex) noexcept -> uint8_t
{
    return autoOffIndex < 2U ? static_cast<uint8_t>(autoOffIndex + 5U) : UINT8_MAX;
}

auto getAutoOffIndexByActuatorIndex(uint8_t actuatorIndex) noexcept -> uint8_t
{
    return actuatorIndex >= 5U && actuatorIndex <= 6U ? static_cast<uint8_t>(actuatorIndex - 5U) : UINT8_MAX;
}

auto getAutoOffTimer(uint8_t actuatorIndex) noexcept -> uint32_t
{
    if (actuatorIndex == 5U)
    {
        return 3600000UL;
    }

    return actuatorIndex == 6U ? 1800000UL : 0UL;
}

auto getLongClickType(uint8_t clickableIndex) noexcept -> constants::LongClickType
{
    static_cast<void>(clickableIndex);
    return constants::LongClickType::NORMAL;
}

auto getSuperLongClickType(uint8_t clickableIndex) noexcept -> constants::SuperLongClickType
{
    static_cast<void>(clickableIndex);
    return constants::SuperLongClickType::NORMAL;
}

auto getLongClickTime(uint8_t clickableIndex) noexcept -> uint16_t
{
    static_cast<void>(clickableIndex);
    return constants::timings::CLICKABLE_LONG_CLICK_TIME_MS;
}

auto getSuperLongClickTime(uint8_t clickableIndex) noexcept -> uint16_t
{
    static_cast<void>(clickableIndex);
    return constants::timings::CLICKABLE_SUPER_LONG_CLICK_TIME_MS;
}

auto getShortClickActuatorLinkCount(uint8_t clickableIndex) noexcept -> uint8_t
{
    if (clickableIndex < 10U)
    {
        return 1U;
    }

    return 0U;
}

auto getLongClickActuatorLinkCount(uint8_t clickableIndex) noexcept -> uint8_t
{
    if ((clickableIndex == 0U) || (clickableIndex >= 2U && clickableIndex <= 3U) || (clickableIndex >= 7U && clickableIndex <= 9U))
    {
        return 2U;
    }

    return 0U;
}

auto getSuperLongClickActuatorLinkCount(uint8_t clickableIndex) noexcept -> uint8_t
{
    static_cast<void>(clickableIndex);
    return 0U;
}

auto getClickActuatorLinkCount(constants::ClickType clickType, uint8_t clickableIndex) noexcept -> uint8_t
{
    switch (clickType)
    {
    case constants::ClickType::SHORT:
        return getShortClickActuatorLinkCount(clickableIndex);
    case constants::ClickType::LONG:
        return getLongClickActuatorLinkCount(clickableIndex);
    case constants::ClickType::SUPER_LONG:
        return getSuperLongClickActuatorLinkCount(clickableIndex);
    default:
        return 0U;
    }
}

auto getShortClickActuatorLink(uint8_t clickableIndex, uint8_t linkIndex) noexcept -> uint8_t
{
    if (linkIndex != 0U)
    {
        return UINT8_MAX;
    }

    if (clickableIndex < 8U)
    {
        return clickableIndex;
    }

    if (clickableIndex == 8U)
    {
        return 0U;
    }

    return clickableIndex == 9U ? 2U : UINT8_MAX;
}

auto getLongClickActuatorLink(uint8_t clickableIndex, uint8_t linkIndex) noexcept -> uint8_t
{
    switch (clickableIndex)
    {
    case 0U:
        if (linkIndex == 0U)
        {
            return 0U;
        }

        return linkIndex == 1U ? 2U : UINT8_MAX;
    case 2U:
        if (linkIndex == 0U)
        {
            return 2U;
        }

        return linkIndex == 1U ? 1U : UINT8_MAX;
    case 3U:
        if (linkIndex == 0U)
        {
            return 3U;
        }

        return linkIndex == 1U ? 7U : UINT8_MAX;
    case 7U:
        if (linkIndex == 0U)
        {
            return 7U;
        }

        return linkIndex == 1U ? 3U : UINT8_MAX;
    case 8U:
        if (linkIndex == 0U)
        {
            return 0U;
        }

        return linkIndex == 1U ? 2U : UINT8_MAX;
    case 9U:
        if (linkIndex == 0U)
        {
            return 2U;
        }

        return linkIndex == 1U ? 1U : UINT8_MAX;
    default:
        return UINT8_MAX;
    }
}

auto getSuperLongClickActuatorLink(uint8_t clickableIndex, uint8_t linkIndex) noexcept -> uint8_t
{
    static_cast<void>(clickableIndex);
    static_cast<void>(linkIndex);
    return UINT8_MAX;
}

auto getClickActuatorLink(constants::ClickType clickType, uint8_t clickableIndex, uint8_t linkIndex) noexcept -> uint8_t
{
    switch (clickType)
    {
    case constants::ClickType::SHORT:
        return getShortClickActuatorLink(clickableIndex, linkIndex);
    case constants::ClickType::LONG:
        return getLongClickActuatorLink(clickableIndex, linkIndex);
    case constants::ClickType::SUPER_LONG:
        return getSuperLongClickActuatorLink(clickableIndex, linkIndex);
    default:
        return UINT8_MAX;
    }
}

auto getIndicatorMode(uint8_t indicatorIndex) noexcept -> constants::IndicatorMode
{
    static_cast<void>(indicatorIndex);
    return constants::IndicatorMode::ANY;
}

auto getIndicatorActuatorLinkCount(uint8_t indicatorIndex) noexcept -> uint8_t
{
    if (indicatorIndex < 3U)
    {
        return 1U;
    }

    return 0U;
}

auto getIndicatorActuatorLink(uint8_t indicatorIndex, uint8_t linkIndex) noexcept -> uint8_t
{
    if (linkIndex != 0U)
    {
        return UINT8_MAX;
    }

    return indicatorIndex < 3U ? static_cast<uint8_t>(indicatorIndex + 4U) : UINT8_MAX;
}

auto getDetailsPayloadSize() noexcept -> uint16_t
{
#ifdef CONFIG_MSG_PACK
    return sizeof(DETAILS_MSGPACK_PAYLOAD);
#else
    return sizeof(DETAILS_JSON_PAYLOAD);
#endif
}

auto getDetailsPayloadByte(uint16_t byteIndex) noexcept -> uint8_t
{
#ifdef CONFIG_MSG_PACK
    if (byteIndex >= sizeof(DETAILS_MSGPACK_PAYLOAD))
    {
        return 0U;
    }
    return LSH_STATIC_CONFIG_READ_BYTE(&DETAILS_MSGPACK_PAYLOAD[byteIndex]);
#else
    if (byteIndex >= sizeof(DETAILS_JSON_PAYLOAD))
    {
        return 0U;
    }
    return LSH_STATIC_CONFIG_READ_BYTE(&DETAILS_JSON_PAYLOAD[byteIndex]);
#endif
}

auto writeDetailsPayload() noexcept -> bool
{
#ifdef CONFIG_MSG_PACK
    return writeGeneratedPayload(DETAILS_MSGPACK_PAYLOAD);
#else
    return writeGeneratedPayload(DETAILS_JSON_PAYLOAD);
#endif
}

auto runShortClick(uint8_t clickableIndex) noexcept -> bool
{
    switch (clickableIndex)
    {
    case 0U:
    {
        return rel0.toggleState();
    }
    case 1U:
    {
        return rel1.toggleState();
    }
    case 2U:
    {
        return rel2.toggleState();
    }
    case 3U:
    {
        return rel3.toggleState();
    }
    case 4U:
    {
        return rel6.toggleState();
    }
    case 5U:
    {
        return rel7.toggleState();
    }
    case 6U:
    {
        return rel8.toggleState();
    }
    case 7U:
    {
        return rel9.toggleState();
    }
    case 8U:
    {
        return rel0.toggleState();
    }
    case 9U:
    {
        return rel2.toggleState();
    }
    default:
        return false;
    }
}

auto runLongClick(uint8_t clickableIndex) noexcept -> bool
{
    switch (clickableIndex)
    {
    case 0U:
    {
        const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel0.getState()) + static_cast<uint8_t>(rel2.getState());
        const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel0.setState(stateToSet);
        anyActuatorChangedState |= rel2.setState(stateToSet);
        return anyActuatorChangedState;
    }
    case 1U:
    {
        return false;
    }
    case 2U:
    {
        const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel2.getState()) + static_cast<uint8_t>(rel1.getState());
        const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel2.setState(stateToSet);
        anyActuatorChangedState |= rel1.setState(stateToSet);
        return anyActuatorChangedState;
    }
    case 3U:
    {
        const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel3.getState()) + static_cast<uint8_t>(rel9.getState());
        const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel3.setState(stateToSet);
        anyActuatorChangedState |= rel9.setState(stateToSet);
        return anyActuatorChangedState;
    }
    case 7U:
    {
        const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel9.getState()) + static_cast<uint8_t>(rel3.getState());
        const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel9.setState(stateToSet);
        anyActuatorChangedState |= rel3.setState(stateToSet);
        return anyActuatorChangedState;
    }
    case 8U:
    {
        const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel0.getState()) + static_cast<uint8_t>(rel2.getState());
        const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel0.setState(stateToSet);
        anyActuatorChangedState |= rel2.setState(stateToSet);
        return anyActuatorChangedState;
    }
    case 9U:
    {
        const uint8_t actuatorsLongOn = static_cast<uint8_t>(rel2.getState()) + static_cast<uint8_t>(rel1.getState());
        const bool stateToSet = (static_cast<uint8_t>(actuatorsLongOn << 1U) < 2U);
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel2.setState(stateToSet);
        anyActuatorChangedState |= rel1.setState(stateToSet);
        return anyActuatorChangedState;
    }
    default:
        return false;
    }
}

auto turnOffAllActuators() noexcept -> bool
{
    bool anyActuatorChangedState = false;
    anyActuatorChangedState |= rel0.setState(false);
    anyActuatorChangedState |= rel1.setState(false);
    anyActuatorChangedState |= rel2.setState(false);
    anyActuatorChangedState |= rel3.setState(false);
    anyActuatorChangedState |= rel6.setState(false);
    anyActuatorChangedState |= rel7.setState(false);
    anyActuatorChangedState |= rel8.setState(false);
    anyActuatorChangedState |= rel9.setState(false);
    return anyActuatorChangedState;
}

auto turnOffUnprotectedActuators() noexcept -> bool
{
    bool anyActuatorChangedState = false;
    anyActuatorChangedState |= rel0.setState(false);
    anyActuatorChangedState |= rel1.setState(false);
    anyActuatorChangedState |= rel2.setState(false);
    anyActuatorChangedState |= rel3.setState(false);
    anyActuatorChangedState |= rel7.setState(false);
    anyActuatorChangedState |= rel8.setState(false);
    anyActuatorChangedState |= rel9.setState(false);
    return anyActuatorChangedState;
}

auto runSuperLongClick(uint8_t clickableIndex) noexcept -> bool
{
    switch (clickableIndex)
    {
    case 8U:
    {
        return turnOffUnprotectedActuators();
    }
    case 9U:
    {
        return turnOffUnprotectedActuators();
    }
    default:
        return false;
    }
}

auto applyPackedActuatorStateByte(uint8_t byteIndex, uint8_t packedByte) noexcept -> bool
{
    switch (byteIndex)
    {
    case 0U:
    {
        bool anyActuatorChangedState = false;
        anyActuatorChangedState |= rel0.setState((packedByte & 1U) != 0U);
        anyActuatorChangedState |= rel1.setState((packedByte & 2U) != 0U);
        anyActuatorChangedState |= rel2.setState((packedByte & 4U) != 0U);
        anyActuatorChangedState |= rel3.setState((packedByte & 8U) != 0U);
        anyActuatorChangedState |= rel6.setState((packedByte & 16U) != 0U);
        anyActuatorChangedState |= rel7.setState((packedByte & 32U) != 0U);
        anyActuatorChangedState |= rel8.setState((packedByte & 64U) != 0U);
        anyActuatorChangedState |= rel9.setState((packedByte & 128U) != 0U);
        return anyActuatorChangedState;
    }
    default:
        return false;
    }
}

auto computeIndicatorState(uint8_t indicatorIndex) noexcept -> bool
{
    switch (indicatorIndex)
    {
    case 0U:
    {
        return rel6.getState();
    }
    case 1U:
    {
        return rel7.getState();
    }
    case 2U:
    {
        return rel8.getState();
    }
    default:
        return false;
    }
}
}  // namespace lsh::core::static_config

void Configurator::configure()
{
    using namespace Debug;
    using constants::NoNetworkClickType;

    DP_CONTEXT();

    Actuators::addActuator(&rel0, 1U, 0U);
    Actuators::addActuator(&rel1, 2U, 1U);
    Actuators::addActuator(&rel2, 3U, 2U);
    Actuators::addActuator(&rel3, 4U, 3U);
    Actuators::addActuator(&rel6, 7U, 4U);
    Actuators::addActuator(&rel7, 8U, 5U);
    Actuators::addActuator(&rel8, 9U, 6U);
    Actuators::addActuator(&rel9, 10U, 7U);

    Clickables::addClickable(&btn0, 1U, 0U);
    Clickables::addClickable(&btn1, 2U, 1U);
    Clickables::addClickable(&btn2, 3U, 2U);
    Clickables::addClickable(&btn3, 4U, 3U);
    Clickables::addClickable(&btn6, 7U, 4U);
    Clickables::addClickable(&btn7, 8U, 5U);
    Clickables::addClickable(&btn8, 9U, 6U);
    Clickables::addClickable(&btn9, 10U, 7U);
    Clickables::addClickable(&btn10, 11U, 8U);
    Clickables::addClickable(&btn11, 12U, 9U);

    Indicators::addIndicator(&light6, 0U);
    Indicators::addIndicator(&light7, 1U);
    Indicators::addIndicator(&light8, 2U);

    rel6.setProtected(true);

    btn0.setClickableLong(true);
    btn1.setClickableLong(true, true, NoNetworkClickType::DO_NOTHING);
    btn2.setClickableLong(true);
    btn3.setClickableLong(true);
    btn9.setClickableLong(true);
    btn10.setClickableLong(true).setClickableSuperLong(true);
    btn11.setClickableLong(true).setClickableSuperLong(true, true, NoNetworkClickType::DO_NOTHING);
}

#undef LSH_STATIC_CONFIG_READ_BYTE
#undef LSH_STATIC_CONFIG_PROGMEM

#endif  // LSH_GENERATED_LSH_CONFIGS_J2_STATIC_CONFIG_HPP_IMPLEMENTATION

#else
#error "j2_static_config.hpp must be included through a static-config pass macro."
#endif
